(function(g){var window=this;var tDa=function(a,b){return g.Wb(a,b)},k6=function(a){g.Zm(a,"zx",g.wb());
return a},l6=function(a,b,c){g.xa(c)||(c=[String(c)]);
g.bn(a.o,b,c)},uDa=function(a,b){var c=[];
g.Lk(b,function(a){try{var b=g.AD.prototype.A.call(this,a,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.u(b)?g.zD(b)&&c.push(a):c.push(a)},a);
return c},vDa=function(a,b){var c=uDa(a,b);
(0,g.D)(c,function(a){g.AD.prototype.remove.call(this,a)},a)},wDa=function(a){if(a.Ld){if(a.Ld.locationOverrideToken)return{locationOverrideToken:a.Ld.locationOverrideToken};
if(null!=a.Ld.latitudeE7&&null!=a.Ld.longitudeE7)return{latitudeE7:a.Ld.latitudeE7,longitudeE7:a.Ld.longitudeE7}}return null},xDa=function(a,b,c,d){var e=new g.Qm(null,void 0);
a&&g.Rm(e,a);b&&g.Sm(e,b);c&&g.Tm(e,c);d&&g.Um(e,d);return e},yDa=function(a){g.eG[a]&&(a=g.eG[a],(0,g.D)(a,function(a){g.cG[a]&&delete g.cG[a]}),a.length=0)},zDa=function(a){var b=g.bG();
if(b)if(b.clear(a),a)yDa(a);else for(var c in g.eG)yDa(c)},m6=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.B=!1;this.capabilities=new window.Set;this.experiments=new window.Set;this.theme="u";new g.Km;this.o=this.A="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",ADa(this,a.capabilities||""),BDa(this,a.experiments||""),this.A=a.remoteControllerUrl||"",
this.o=a.localChannelEncryptionKey||"")},ADa=function(a,b){a.capabilities.clear();
(0,g.Wd)(b.split(","),g.Da(tDa,CDa)).forEach(function(b){a.capabilities.add(b)})},BDa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(b){a.experiments.add(b)})},n6=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},o6=function(a,b){return!!b&&(a.id==b||a.uuid==b)},DDa=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},EDa=function(a){return new n6(a)},FDa=function(a){return g.xa(a)?(0,g.I)(a,EDa):[]},p6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},q6=function(a){return g.xa(a)?"["+(0,g.I)(a,p6).join(",")+"]":"null"},r6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},GDa=function(a){return(0,g.I)(a,function(a){return{key:a.id,
name:a.name}})},s6=function(a,b){return g.Ja(a,function(a){return a||b?!a!=!b?!1:a.id==b.id:!0})},t6=function(a,b){return g.Ja(a,function(a){return o6(a,b)})},HDa=function(){var a=(0,g.oH)();
a&&vDa(a,a.o.fe(!0))},u6=function(){var a=g.rH("yt-remote-connected-devices")||[];
g.fb(a);return a},IDa=function(a){if(g.Oa(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.I)(a,function(a,b){return 0==b?a:a.substring(c.length)})},JDa=function(a){g.qH("yt-remote-connected-devices",a,86400)},w6=function(){if(v6)return v6;
var a=g.rH("yt-remote-device-id");a||(a=r6(),g.qH("yt-remote-device-id",a,31536E3));for(var b=u6(),c=1,d=a;g.Na(b,d);)c++,d=a+"#"+c;return v6=d},x6=function(){var a=u6(),b=w6();
g.Na(a,b);g.tH()&&g.ib(a,b);a=IDa(a);if(g.Oa(a))try{g.NG("remote_sid")}catch(c){}else try{g.MG("remote_sid",a.join(","),-1)}catch(c){}},KDa=function(){return g.rH("yt-remote-session-browser-channel")},LDa=function(){return g.rH("yt-remote-local-screens")||[]},MDa=function(){g.qH("yt-remote-lounge-token-expiration",!0,86400)},NDa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.I)(LDa(),function(a){return a.loungeToken}),c=(0,g.I)(a,function(a){return a.loungeToken});
(0,g.xm)(c,function(a){return!g.Na(b,a)})&&MDa();
g.qH("yt-remote-local-screens",a,31536E3)},ODa=function(a,b){g.qH("yt-remote-session-browser-channel",a);
g.qH("yt-remote-session-screen-id",b);var c=u6(),d=w6();g.Na(c,d)||c.push(d);JDa(c);x6()},y6=function(a){a||(g.sH("yt-remote-session-screen-id"),g.sH("yt-remote-session-video-id"));
x6();a=u6();g.Sa(a,w6());JDa(a)},PDa=function(){if(!z6){var a=g.LD();
a&&(z6=new g.uD(a))}return z6?!!z6.get("yt-remote-use-staging-server"):!1},QDa=function(){var a=window.document.createElement("a");
g.id(a,"https://www.gstatic.com/cv/js/sender/v1/cast_sender.js");a=a.href.replace(/^[a-zA-Z]+:\/\//,"//");return"js-"+g.Ab(a)},RDa=function(a,b,c){c=void 0===c?null:c;
var d=g.Pd("SCRIPT");d.id=a;d.onload=function(){b&&(0,window.setTimeout)(b,0)};
d.onreadystatechange=function(){switch(d.readyState){case "loaded":case "complete":d.onload()}};
c&&d.setAttribute("nonce",c);g.kd(d,g.ne("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"));a=window.document.getElementsByTagName("head")[0]||window.document.body;a.insertBefore(d,a.firstChild);return d},SDa=function(a){a=void 0===a?null:a;
var b=QDa(),c=window.document.getElementById(b),d=c&&g.nF(c,"loaded");d||c&&!d||(c=RDa(b,function(){g.nF(c,"loaded")||(g.mF(c,"loaded","true"),g.iG(b),g.mE(g.Da(zDa,b),0))},a))},TDa=function(){var a=void 0===a?null:a;
window.spf?window.spf.script.load("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js","",void 0):SDa(a)},A6=function(a){return!!window.document.currentScript&&(-1!=window.document.currentScript.src.indexOf("?"+a)||-1!=window.document.currentScript.src.indexOf("&"+a))},UDa=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},B6=function(a){a.length?VDa(a.shift(),function(){B6(a)}):C6()},WDa=function(a){return"chrome-extension://"+a+D6},VDa=function(a,
b,c){var d=window.document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(window.document.head||window.document.documentElement).appendChild(d)},E6=function(a){return 0<=window.navigator.userAgent.indexOf(a)},C6=function(){var a=UDa();
a&&a(!1,"No cast extension found")},F6=function(){if(XDa){var a=2,b=UDa(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;VDa("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",C6,c)}},YDa=function(){var a=window.__gCrWeb&&window.__gCrWeb.message&&window.__gCrWeb.message.invokeOnHost;
a&&(F6(),a({command:"cast.sender.init"}))},ZDa=function(){F6();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);B6(["//www.gstatic.com/eureka/clank/"+(a?(0,window.parseInt)(a[1],10):0)+D6,"//www.gstatic.com/eureka/clank"+D6])},G6=function(a,b,c){g.L.call(this);
this.F=null!=c?(0,g.B)(a,c):a;this.Dd=b;this.D=(0,g.B)(this.ML,this);this.o=!1;this.A=0;this.B=this.Ea=null;this.C=[]},H6=function(){},I6=function(a,b,c,d){this.o=a;
this.B=b;this.G=c;this.F=d||1;this.C=45E3;this.Z=new g.fn(this);this.A=new g.Cg;this.A.setInterval(250)},aEa=function(a,b,c){a.wk=1;
a.Oh=k6(b.clone());a.Dj=c;a.D=!0;$Da(a,null)},J6=function(a,b,c,d,e){a.wk=1;
a.Oh=k6(b.clone());a.Dj=null;a.D=c;e&&(a.KF=!1);$Da(a,d)},$Da=function(a,b){a.vl=(0,g.H)();
K6(a);a.si=a.Oh.clone();l6(a.si,"t",a.F);a.bo=0;a.Xc=a.o.jt(a.o.Un()?b:null);0<a.Wt&&(a.Xq=new g.ql((0,g.B)(a.eH,a,a.Xc),a.Wt));a.Z.W(a.Xc,"readystatechange",a.eX);var c=a.ej?g.dc(a.ej):{};a.Dj?(a.Rr="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.Xc.send(a.si,a.Rr,a.Dj,c)):(a.Rr="GET",a.KF&&!g.Kd&&(c.Connection="close"),a.Xc.send(a.si,a.Rr,null,c));a.o.Jf(1)},dEa=function(a,b,c){for(var d=!0;!a.Oi&&a.bo<c.length;){var e=bEa(a,c);
if(e==L6){4==b&&(a.Ph=4,M6(15),d=!1);break}else if(e==cEa){a.Ph=4;M6(16);d=!1;break}else N6(a,e)}4==b&&0==c.length&&(a.Ph=1,M6(17),d=!1);a.Qf=a.Qf&&d;d||(O6(a),P6(a))},bEa=function(a,b){var c=a.bo,d=b.indexOf("\n",c);
if(-1==d)return L6;c=Number(b.substring(c,d));if((0,window.isNaN)(c))return cEa;d+=1;if(d+c>b.length)return L6;var e=b.substr(d,c);a.bo=d+c;return e},fEa=function(a,b){a.vl=(0,g.H)();
K6(a);var c=b?window.location.hostname:"";a.si=a.Oh.clone();g.Zm(a.si,"DOMAIN",c);g.Zm(a.si,"t",a.F);try{a.Rf=new window.ActiveXObject("htmlfile")}catch(n){O6(a);a.Ph=7;M6(22);P6(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in Q6)k=Q6[l];else if(l in eEa)k=Q6[l]=eEa[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=
m.toString(16).toUpperCase()}k=Q6[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.ld(g.Bc("b/12014412"),d+"</body></html>");a.Rf.open();a.Rf.write(g.bd(c));a.Rf.close();a.Rf.parentWindow.m=(0,g.B)(a.mW,a);a.Rf.parentWindow.d=(0,g.B)(a.TE,a,!0);a.Rf.parentWindow.rpcClose=(0,g.B)(a.TE,a,!1);c=a.Rf.createElement("DIV");a.Rf.parentWindow.document.body.appendChild(c);d=g.Pc(a.si.toString());d=g.pb(g.Mc(d));d=g.ld(g.Bc("b/12014412"),'<iframe src="'+d+'"></iframe>');g.hd(c,g.bd(d));a.o.Jf(1)},
K6=function(a){a.Jx=(0,g.H)()+a.C;
gEa(a,a.C)},gEa=function(a,b){if(null!=a.Ml)throw Error("WatchDog timer not null");
a.Ml=R6((0,g.B)(a.DW,a),b)},S6=function(a){a.Ml&&(g.x.clearTimeout(a.Ml),a.Ml=null)},P6=function(a){a.o.VA()||a.Oi||a.o.Hq(a)},O6=function(a){S6(a);
g.mf(a.Xq);a.Xq=null;a.A.stop();g.mn(a.Z);if(a.Xc){var b=a.Xc;a.Xc=null;b.abort();b.dispose()}a.Rf&&(a.Rf=null)},N6=function(a,b){try{a.o.LE(a,b),a.o.Jf(4)}catch(c){}},iEa=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;hEa(a,b,function(e){e?c(!0):g.x.setTimeout(function(){iEa(a,b,c,d,f)},f)})}},hEa=function(a,b,c){var d=new window.Image;
d.onload=function(){try{T6(d),c(!0)}catch(e){}};
d.onerror=function(){try{T6(d),c(!1)}catch(e){}};
d.onabort=function(){try{T6(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{T6(d),c(!1)}catch(e){}};
g.x.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
d.src=a},T6=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},jEa=function(a){this.o=a;
this.A=new H6},kEa=function(a){var b=U6(a.o,a.Ul,"/mail/images/cleardot.gif");
k6(b);iEa(b.toString(),5E3,(0,g.B)(a.QK,a),3,2E3);a.Jf(1)},W6=function(a){var b=a.o.J;
if(null!=b)M6(5),b?(M6(11),V6(a.o,a,!1)):(M6(12),V6(a.o,a,!0));else if(a.Ke=new I6(a,void 0,void 0,void 0),a.Ke.ej=a.Ut,b=a.o,b=U6(b,b.Un()?a.Mm:null,a.Vt),M6(5),!g.Id||g.tc(10))l6(b,"TYPE","xmlhttp"),J6(a.Ke,b,!1,a.Mm,!1);else{l6(b,"TYPE","html");var c=a.Ke;a=!!a.Mm;c.wk=3;c.Oh=k6(b.clone());fEa(c,a)}},X6=function(a,b,c){this.o=1;
this.A=[];this.C=[];this.D=new H6;this.H=a||null;this.J=null!=b?b:null;this.F=c||!1},lEa=function(a,b){this.o=a;
this.map=b;this.context=null},mEa=function(a){g.pf.call(this,"statevent",a)},nEa=function(a,b){g.pf.call(this,"timingevent",a);
this.size=b},oEa=function(a){g.pf.call(this,"serverreachability",a)},rEa=function(a){pEa(a);
if(3==a.o){var b=a.Gn++,c=a.tp.clone();g.Zm(c,"SID",a.B);g.Zm(c,"RID",b);g.Zm(c,"TYPE","terminate");Y6(a,c);b=new I6(a,a.B,b,void 0);b.wk=2;b.Oh=k6(c.clone());(new window.Image).src=b.Oh;b.vl=(0,g.H)();K6(b)}qEa(a)},sEa=function(a){a.mL(1,0);
a.tp=U6(a,null,a.Tt);Z6(a)},pEa=function(a){a.Eh&&(a.Eh.abort(),a.Eh=null);
a.Ac&&(a.Ac.cancel(),a.Ac=null);a.Lg&&(g.x.clearTimeout(a.Lg),a.Lg=null);$6(a);a.ke&&(a.ke.cancel(),a.ke=null);a.Jh&&(g.x.clearTimeout(a.Jh),a.Jh=null)},tEa=function(a,b){if(0==a.o)throw Error("Invalid operation: sending map when state is closed");
a.A.push(new lEa(a.YR++,b));2!=a.o&&3!=a.o||Z6(a)},Z6=function(a){a.ke||a.Jh||(a.Jh=R6((0,g.B)(a.RE,a),0),a.kk=0)},vEa=function(a,b){if(1==a.o){if(!b){a.Gn=Math.floor(1E5*Math.random());
var c=a.Gn++,d=new I6(a,"",c,void 0);d.ej=null;var e=a7(a),f=a.tp.clone();g.Zm(f,"RID",c);g.Zm(f,"CVER","1");Y6(a,f);aEa(d,f,e);a.ke=d;a.o=2}}else 3==a.o&&(b?uEa(a,b):0==a.A.length||a.ke||uEa(a))},uEa=function(a,b){if(b)if(6<a.Qi){a.A=a.C.concat(a.A);
a.C.length=0;var c=a.Gn-1;var d=a7(a)}else c=b.G,d=b.Dj;else c=a.Gn++,d=a7(a);var e=a.tp.clone();g.Zm(e,"SID",a.B);g.Zm(e,"RID",c);g.Zm(e,"AID",a.Mk);Y6(a,e);c=new I6(a,a.B,c,a.kk+1);c.ej=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.ke=c;aEa(c,e,d)},Y6=function(a,b){if(a.Cd){var c=a.Cd.CA();
c&&g.Ib(c,function(a,c){g.Zm(b,c,a)})}},a7=function(a){var b=Math.min(a.A.length,1E3),c=["count="+b];
if(6<a.Qi&&0<b){var d=a.A[0].o;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.A[e].o,k=a.A[e].map;f=6>=a.Qi?e:f-d;try{g.Ib(k,function(a,b){c.push("req"+f+"_"+b+"="+(0,window.encodeURIComponent)(a))})}catch(l){c.push("req"+f+"_type="+(0,window.encodeURIComponent)("_badmap"))}}a.C=a.C.concat(a.A.splice(0,b));
return c.join("&")},wEa=function(a){a.Ac||a.Lg||(a.G=1,a.Lg=R6((0,g.B)(a.QE,a),0),a.Yj=0)},b7=function(a){if(a.Ac||a.Lg||3<=a.Yj)return!1;
a.G++;a.Lg=R6((0,g.B)(a.QE,a),xEa(a,a.Yj));a.Yj++;return!0},V6=function(a,b,c){a.Pr=c;
a.ig=b.Zg;a.F||sEa(a)},$6=function(a){null!=a.Ri&&(g.x.clearTimeout(a.Ri),a.Ri=null)},xEa=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},c7=function(a,b){if(2==b||9==b){var c=null;
a.Cd&&(c=null);var d=(0,g.B)(a.SX,a);c||(c=new g.Qm("//www.google.com/images/cleardot.gif"),k6(c));hEa(c.toString(),1E4,d)}else M6(2);yEa(a,b)},yEa=function(a,b){a.o=0;
a.Cd&&a.Cd.Dz(b);qEa(a);pEa(a)},qEa=function(a){a.o=0;
a.ig=-1;if(a.Cd)if(0==a.C.length&&0==a.A.length)a.Cd.Qs();else{g.Wa(a.C);var b=g.Wa(a.A);a.C.length=0;a.A.length=0;a.Cd.Qs(b)}},U6=function(a,b,c){var d=g.$m(c);
if(""!=d.A)b&&g.Sm(d,b+"."+d.A),g.Tm(d,d.D);else{var e=window.location;d=xDa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.sm&&g.Ib(a.sm,function(a,b){g.Zm(d,b,a)});
g.Zm(d,"VER",a.Qi);Y6(a,d);return d},R6=function(a,b){if(!g.za(a))throw Error("Fn must not be null and must be a function");
return g.x.setTimeout(function(){a()},b)},M6=function(a){d7.dispatchEvent(new mEa(d7,a))},zEa=function(){},AEa=function(a,b){this.action=a;
this.params=b||{}},e7=function(a,b){g.L.call(this);
this.o=new g.U(this.dW,0,this);g.M(this,this.o);this.Dd=5E3;this.A=0;if(g.za(a))b&&(a=(0,g.B)(a,b));else if(a&&g.za(a.handleEvent))a=(0,g.B)(a.handleEvent,a);else throw Error("Invalid listener argument");this.B=a},f7=function(a,b,c){this.L=a;
this.F=b;this.B=new g.tD;this.A=new e7(this.BY,this);this.o=this.gb=null;this.K=!1;this.D=null;this.J="";this.H=this.C=0;this.G=[];this.N=c||!1},BEa=function(a){return{firstTestResults:[""],
secondTestResults:!a.o.Pr,sessionId:a.o.B,arrayId:a.o.Mk}},CEa=function(a,b){a.H=b||0;
a.A.stop();a.o&&(3==a.o.o&&vEa(a.o),rEa(a.o));a.H=0},g7=function(a){return!!a.o&&3==a.o.o},DEa=function(a,b){(a.F.loungeIdToken=b)||a.A.stop()},h7=function(a){this.port=this.domain="";
this.o="/api/lounge";this.A=!0;a=a||window.document.location.href;var b=g.Rg(a)||"";b&&(this.port=":"+b);this.domain=g.Qg(a)||"";a=g.Gb;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.zb(a,"10.0")&&(this.A=!1))},i7=function(a,b){var c=a.o;
if(g.u(void 0)?0:a.A)c="https://"+a.domain+a.port+a.o;return g.$g(c+b,{})},j7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Da(a.C,d,!0),onError:g.Da(a.B,e),Hd:g.Da(a.D,e)};c&&(a.Rb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.DE(b,a)},HEa=function(){var a=EEa;
FEa();k7.push(a);GEa(k7)},l7=function(a,b){FEa();
var c=k7,d=IEa(a,String(b));g.Oa(c)?JEa(d):(GEa(c),(0,g.D)(c,function(a){a(d)}))},FEa=function(){k7||(k7=g.y("yt.mdx.remote.debug.handlers_")||[],g.ua("yt.mdx.remote.debug.handlers_",k7,void 0))},JEa=function(a){var b=(m7+1)%50;
m7=b;n7[b]=a;o7||(o7=49==b)},GEa=function(a){var b=n7;
if(b[0]){var c=m7,d=o7?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.D)(a,function(a){a(e)})}while(d!=c);
n7=Array(50);m7=-1;o7=!1}},IEa=function(a,b){var c=((0,g.H)()-KEa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},p7=function(a){g.VF.call(this);
this.G=a;this.o=[]},LEa=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.o.push(b);return!0},MEa=function(a,b){var c=a.o.length!=b.length;
a.o=(0,g.Wd)(a.o,function(a){return!!s6(b,a)});
for(var d=0,e=b.length;d<e;d++)c=LEa(a,b[d])||c;return c},NEa=function(a,b){var c=a.o.length;
a.o=(0,g.Wd)(a.o,function(a){return!(a||b?!a!=!b?0:a.id==b.id:1)});
return a.o.length<c},q7=function(a,b,c,d){g.VF.call(this);
this.F=a;this.D=b;this.B=c;this.C=d;this.A=0;this.o=null;this.Ea=window.NaN},s7=function(a){p7.call(this,"LocalScreenService");
this.B=a;this.A=window.NaN;r7(this);this.info("Initializing with "+q6(this.o))},OEa=function(a){if(a.o.length){var b=(0,g.I)(a.o,function(a){return a.id}),c=i7(a.B,"/pairing/get_lounge_token_batch");
j7(a.B,c,{screen_ids:b.join(",")},(0,g.B)(a.ZL,a),(0,g.B)(a.YL,a))}},r7=function(a){var b=FDa(LDa());
b=(0,g.Wd)(b,function(a){return!a.uuid});
return MEa(a,b)},t7=function(a,b){NDa((0,g.I)(a.o,DDa));
b&&MDa()},v7=function(a,b){g.VF.call(this);
this.F=b;var c=g.rH("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.F(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.Na(c,l)}this.o=d;this.D=a;this.B=this.C=window.NaN;this.A=null;u7("Initialized with "+g.Ig(this.o))},PEa=function(a,b,c){var d=i7(a.D,"/pairing/get_screen_availability");
j7(a.D,d,{lounge_token:b.token},(0,g.B)(function(a){a=a.screens||[];for(var d=0,e=a.length;d<e;++d)if(a[d].loungeToken==b.token){c("online"==a[d].status);return}c(!1)},a),(0,g.B)(function(){c(!1)},a))},w7=function(a,b){a:if(g.Ob(b)!=g.Ob(a.o))var c=!1;
else{c=g.Rb(b);for(var d=0,e=c.length;d<e;++d)if(!a.o[c[d]]){c=!1;break a}c=!0}c||(u7("Updated online screens: "+g.Ig(a.o)),a.o=b,a.V("screenChange"));QEa(a)},x7=function(a){(0,window.isNaN)(a.B)||g.oE(a.B);
a.B=g.mE((0,g.B)(a.Mw,a),0<a.C&&a.C<(0,g.H)()?2E4:1E4)},u7=function(a){l7("OnlineScreenService",a)},REa=function(a){var b={};
(0,g.D)(a.F(),function(a){a.token?b[a.token]=a.id:this.sc("Requesting availability of screen w/o lounge token.")});
return b},QEa=function(a){a=g.Rb(g.Jb(a.o,function(a){return a}));
g.fb(a);a.length?g.qH("yt-remote-online-screen-ids",a.join(","),60):g.sH("yt-remote-online-screen-ids")},y7=function(a){p7.call(this,"ScreenService");
this.F=a;this.A=this.B=null;this.C=[];this.D={};SEa(this)},UEa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.D[b]);var k=a.Ee();if(k=(c?t6(k,c):null)||t6(k,b)){k.uuid=b;var l=z7(a,k);PEa(a.A,l,function(a){e(a?l:null)})}else c?TEa(a,c,(0,g.B)(function(a){var f=z7(this,new n6({name:d,
screenId:c,loungeToken:a,dialId:b||""}));PEa(this.A,f,function(a){e(a?f:null)})},a),f):e(null)},VEa=function(a,b){for(var c=0,d=a.o.length;c<d;++c)if(a.o[c].name==b)return a.o[c];
return null},TEa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={Rb:{screen_ids:b},method:"POST",context:a,onSuccess:function(a,e){var f=e&&e.screens||[];f[0]&&f[0].screenId==b?c(f[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.DE(i7(a.F,"/pairing/get_lounge_token_batch"),e)},WEa=function(a){a.o=a.B.Ee();
var b=a.D,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.o.length;b<d;++b){var e=a.o[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+q6(a.o))},SEa=function(a){A7(a);
a.B=new s7(a.F);a.B.subscribe("screenChange",(0,g.B)(a.nM,a));WEa(a);a.C=FDa(g.rH("yt-remote-automatic-screen-cache")||[]);A7(a);a.info("Initializing automatic screens: "+q6(a.C));a.A=new v7(a.F,(0,g.B)(a.Ee,a,!0));a.A.subscribe("screenChange",(0,g.B)(function(){this.V("onlineScreenChange")},a))},z7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=t6(a.C,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.C.push(b),g.qH("yt-remote-automatic-screen-cache",(0,g.I)(a.C,DDa)));A7(a);a.D[b.uuid]=b.id;g.qH("yt-remote-device-id-map",a.D,31536E3);return b},A7=function(a){a.D=g.rH("yt-remote-device-id-map")||{}},B7=function(a,b,c){g.VF.call(this);
this.N=c;this.J=a;this.A=b;this.B=null},C7=function(a,b){l7(a.N,b)},D7=function(a,b){B7.call(this,a,b,"CastSession");
this.o=null;this.C=0;this.F=(0,g.B)(this.HY,this);this.D=(0,g.B)(this.PW,this);this.C=g.mE((0,g.B)(function(){XEa(this,null)},this),12E4)},YEa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.Ig(void 0));
var b={type:"getMdxSessionStatus"};a.o?a.o.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.A,(0,g.B)(function(){C7(this,"Failed to send message: getMdxSessionStatus.")},a)):C7(a,"Sending yt message without session: "+g.Ig(b))},XEa=function(a,b){g.oE(a.C);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.B||a.B.id!=b){var c=(0,g.B)(a.Iq,a),d=(0,g.B)(a.Je,a);a.LA(b,c,d,5)}}else a.Je(Error("Waiting for session status timed out."))},E7=function(a,b,c){B7.call(this,a,b,"DialSession");
this.C=this.H=null;this.K="";this.O=c;this.D=null;this.G=g.A;this.F=window.NaN;this.L=(0,g.B)(this.KY,this);this.o=g.A},ZEa=function(a){a.o=a.J.lH(a.K,a.A.label,a.A.friendlyName,(0,g.B)(function(a){this.o=g.A;
this.Iq(a)},a),(0,g.B)(function(a){this.o=g.A;
this.Je(a)},a))},$Ea=function(a){var b={};
b.pairingCode=a.K;b.theme=a.O;if(a.D){var c=a.D.currentTime||0;b.v=a.D.videoId;b.t=c}PDa()&&(b.env_useStageMdx=1);return g.Yg(b)},F7=function(a,b){B7.call(this,a,b,"ManualSession");
this.o=g.mE((0,g.B)(this.Ok,this,null),150)},G7=function(a,b,c,d){g.VF.call(this);
this.A=a;this.G=b||"233637DE";this.F=c||"cl";this.H=d||!1;this.o=null;this.D=!1;this.B=[];this.C=(0,g.B)(this.oV,this)},aFa=function(a,b){return b?g.Ja(a.B,function(a){return o6(b,a.label)},a):null},H7=function(a){l7("Controller",a)},EEa=function(a){window.chrome&&window.chrome.cast&&window.chrome.cast.logMessage&&window.chrome.cast.logMessage(a)},I7=function(a){return a.D||!!a.B.length||!!a.o},J7=function(a,b,c){b!=a.o&&(g.mf(a.o),(a.o=b)?(c?a.V("yt-remote-cast2-receiver-resumed",b.A):a.V("yt-remote-cast2-receiver-selected",
b.A),b.subscribe("sessionScreen",(0,g.B)(a.OE,a,b)),b.B?a.V("yt-remote-cast2-session-change",b.B):c&&a.o.Ok(null)):a.V("yt-remote-cast2-session-change",null))},bFa=function(a){var b=a.A.kH(),c=a.o&&a.o.A;
a=(0,g.I)(b,function(a){c&&o6(a,c.label)&&(c=null);var b=a.uuid?a.uuid:a.id,d=aFa(this,a);d?(d.label=b,d.friendlyName=a.name):(d=new window.chrome.cast.Receiver(b,a.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM);return d},a);
c&&(c.receiverType!=window.chrome.cast.ReceiverType.CUSTOM&&(c=new window.chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=window.chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},hFa=function(a,b,c,d,e,f,k){cFa()?dFa(b,e,f,k)&&(L7(!0),window.chrome&&window.chrome.cast&&window.chrome.cast.isAvailable?eFa(a,c):(window.__onGCastApiAvailable=function(b,d){b?eFa(a,c):(M7("Failed to load cast API: "+d),N7(!1),L7(!1),g.sH("yt-remote-cast-available"),g.sH("yt-remote-cast-receiver"),fFa(),
c(!1))},d?TDa():E6("CriOS")?YDa():E6("Android")&&E6("Chrome/")&&window.navigator.presentation?ZDa():window.chrome&&window.navigator.presentation&&!E6("Edge")?(F6(),B6(gFa.map(WDa))):C6())):K7("Cannot initialize because not running Chrome")},fFa=function(){K7("dispose");
var a=O7();a&&a.dispose();g.ua("yt.mdx.remote.cloudview.instance_",null,void 0);iFa(!1);g.gG(P7);P7.length=0},Q7=function(){return!!g.rH("yt-remote-cast-installed")},jFa=function(){var a=g.rH("yt-remote-cast-receiver");
return a?a.friendlyName:null},kFa=function(){K7("clearCurrentReceiver");
g.sH("yt-remote-cast-receiver")},lFa=function(){return Q7()?O7()?O7().getCastSession():(M7("getCastSelector: Cast is not initialized."),null):(M7("getCastSelector: Cast API is not installed!"),null)},S7=function(){Q7()?O7()?R7()?(K7("Requesting cast selector."),O7().requestSession()):(K7("Wait for cast API to be ready to request the session."),P7.push(g.fG("yt-remote-cast2-api-ready",S7))):M7("requestCastSelector: Cast is not initialized."):M7("requestCastSelector: Cast API is not installed!")},T7=
function(a,b){R7()?O7().setConnectedScreenStatus(a,b):M7("setConnectedScreenStatus called before ready.")},cFa=function(){var a=0<=g.Gb.search(/ (CrMo|Chrome|CriOS)\//);
return g.HI||a},mFa=function(a,b){O7().init(a,b)},dFa=function(a,b,c,d){var e=!1;
O7()||(a=new G7(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(a){g.qH("yt-remote-cast-available",a);g.jG("yt-remote-cast2-availability-change",a)}),a.subscribe("yt-remote-cast2-receiver-selected",function(a){K7("onReceiverSelected: "+a.friendlyName);
g.qH("yt-remote-cast-receiver",a);g.jG("yt-remote-cast2-receiver-selected",a)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(a){K7("onReceiverResumed: "+a.friendlyName);
g.qH("yt-remote-cast-receiver",a)}),a.subscribe("yt-remote-cast2-session-change",function(a){K7("onSessionChange: "+p6(a));
a||g.sH("yt-remote-cast-receiver");g.jG("yt-remote-cast2-session-change",a)}),g.ua("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
K7("cloudview.createSingleton_: "+e);return e},O7=function(){return g.y("yt.mdx.remote.cloudview.instance_")},eFa=function(a,b){N7(!0);
L7(!1);mFa(a,function(a){a?(iFa(!0),g.iG("yt-remote-cast2-api-ready")):(M7("Failed to initialize cast API."),N7(!1),g.sH("yt-remote-cast-available"),g.sH("yt-remote-cast-receiver"),fFa());b(a)})},K7=function(a){l7("cloudview",a)},M7=function(a){l7("cloudview",a)},N7=function(a){K7("setCastInstalled_ "+a);
g.qH("yt-remote-cast-installed",a)},R7=function(){return!!g.y("yt.mdx.remote.cloudview.apiReady_")},iFa=function(a){K7("setApiReady_ "+a);
g.ua("yt.mdx.remote.cloudview.apiReady_",a,void 0)},L7=function(a){g.ua("yt.mdx.remote.cloudview.initializing_",a,void 0)},U7=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.o=-1;this.muted=!1;this.audioTrackId=null;this.G=this.H=0;this.A=null;this.hasNext=this.mg=!1;this.K=this.J=this.B=this.D=0;this.C=window.NaN;this.F=!1;this.reset(a)},V7=function(a){a.audioTrackId=null;
a.A=null;a.o=-1;a.mg=!1;a.hasNext=!1;a.H=0;a.G=(0,g.H)();a.D=0;a.B=0;a.J=0;a.K=0;a.C=window.NaN;a.F=!1},W7=function(a){return a.qb()?((0,g.H)()-a.G)/1E3:0},X7=function(a,b){a.H=b;
a.G=(0,g.H)()},Y7=function(a){switch(a.o){case 1:case 1081:return((0,g.H)()-a.G)/1E3+a.H;
case -1E3:return 0}return a.H},Z7=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&V7(a)},$7=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.o;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.ec(a.A);b.hasPrevious=a.mg;b.hasNext=a.hasNext;b.playerTime=a.H;b.playerTimeAt=a.G;b.seekableStart=a.D;b.seekableEnd=a.B;b.duration=a.J;b.loadedTime=a.K;b.liveIngestionTime=a.C;return b},b8=function(a,b){g.VF.call(this);
this.o=0;this.C=a;this.F=[];this.D=new g.KC;this.B=this.A=null;this.J=(0,g.B)(this.HS,this);this.G=(0,g.B)(this.Jn,this);this.H=(0,g.B)(this.GS,this);this.K=(0,g.B)(this.US,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.Qx,this),nFa(this))):c=3;0!=c&&(b?this.Qx(c):g.mE((0,g.B)(function(){this.Qx(c)},this),0));
var d=lFa();d&&a8(this,d);this.subscribe("yt-remote-cast2-session-change",this.K)},c8=function(a){return new U7(a.C.getPlayerContextData())},nFa=function(a){(0,g.D)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(a){this.F.push(this.C.subscribe(a,g.Da(this.jV,a),this))},a)},oFa=function(a){(0,g.D)(a.F,function(a){this.C.unsubscribeByKey(a)},a);
a.F.length=0},d8=function(a,b){50>a.D.Bc()&&g.MC(a.D,b)},f8=function(a,b,c){var d=c8(a);
X7(d,c);-1E3!=d.o&&(d.o=b);e8(a,d)},g8=function(a,b,c){a.C.sendMessage(b,c)},e8=function(a,b){oFa(a);
a.C.setPlayerContextData($7(b));nFa(a)},a8=function(a,b){a.B&&(a.B.removeUpdateListener(a.J),a.B.removeMediaListener(a.G),a.Jn(null));
a.B=b;a.B&&(l7("CP","Setting cast session: "+a.B.sessionId),a.B.addUpdateListener(a.J),a.B.addMediaListener(a.G),a.B.media.length&&a.Jn(a.B.media[0]))},pFa=function(a){var b=a.A.media,c=a.A.customData;
if(b&&c){var d=c8(a);b.contentId!=d.videoId&&l7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.o=c.playerState;X7(d,a.A.getEstimatedTime());e8(a,d)}else l7("CP","No cast media video. Ignoring state update.")},h8=function(a,b,c){return(0,g.B)(function(a){this.sc("Failed to "+b+" with cast v2 channel. Error code: "+a.code);
a.code!=window.chrome.cast.ErrorCode.TIMEOUT&&(this.sc("Retrying "+b+" using MDx browser channel."),g8(this,b,c))},a)},i8=function(a,b,c){g.VF.call(this);
this.D=window.NaN;this.O=!1;this.K=this.J=this.L=this.N=window.NaN;this.Y=[];this.C=this.G=this.B=this.ib=this.o=null;this.sa=a;this.Y.push(g.EF(window,"beforeunload",(0,g.B)(this.QL,this)));this.A=[];this.ib=new U7;this.da=b.id;this.o=qFa(this,c);this.o.subscribe("handlerOpened",this.LS,this);this.o.subscribe("handlerClosed",this.IS,this);this.o.subscribe("handlerError",this.JS,this);this.o.subscribe("handlerMessage",this.KS,this);DEa(this.o,b.token);this.subscribe("remoteQueueChange",function(){var a=
this.ib.videoId;g.tH()&&g.qH("yt-remote-session-video-id",a)},this)},j8=function(a){l7("conn",a)},qFa=function(a,b){return new f7(i7(a.sa,"/bc"),b)},k8=function(a,b){a.V("proxyStateChange",b)},rFa=function(a){a.D=g.mE((0,g.B)(function(){j8("Connecting timeout");
this.F(1)},a),2E4)},l8=function(a){g.oE(a.D);
a.D=window.NaN},m8=function(a){g.oE(a.N);
a.N=window.NaN},sFa=function(a){n8(a);
a.L=g.mE((0,g.B)(function(){o8(this,"getNowPlaying")},a),2E4)},n8=function(a){g.oE(a.L);
a.L=window.NaN},uFa=function(a,b){b&&(l8(a),m8(a));
b==(g7(a.o)&&(0,window.isNaN)(a.D))?b&&(k8(a,1),o8(a,"getSubtitlesTrack")):b?(a.aa()&&a.ib.reset(),k8(a,1),o8(a,"getNowPlaying"),tFa(a)):a.F(1)},vFa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.ib.videoId&&(g.Zb(b.params)?a.ib.A=null:a.ib.A=b.params,a.V("remotePlayerChange"))},wFa=function(a,b){var c=b.params.videoId||b.params.video_id,d=(0,window.parseInt)(b.params.currentIndex,10);
a.ib.listId=b.params.listId||a.ib.listId;Z7(a.ib,c,d);a.V("remoteQueueChange")},yFa=function(a,b){b.params=b.params||{};
wFa(a,b);xFa(a,b);a.V("autoplayDismissed")},xFa=function(a,b){var c=(0,window.parseInt)(b.params.currentTime||b.params.current_time,10);
X7(a.ib,(0,window.isNaN)(c)?0:c);c=(0,window.parseInt)(b.params.state,10);c=(0,window.isNaN)(c)?-1:c;-1==c&&-1E3==a.ib.o&&(c=-1E3);a.ib.o=c;c=Number(b.params.loadedTime);a.ib.K=(0,window.isNaN)(c)?0:c;c=Number(b.params.duration);a.ib.J=(0,window.isNaN)(c)?0:c;c=a.ib;var d=Number(b.params.liveIngestionTime);c.C=d;c.F=(0,window.isNaN)(d)?!1:!0;c=a.ib;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.D=(0,window.isNaN)(d)?0:d;c.B=(0,window.isNaN)(e)?0:e;1==a.ib.o?sFa(a):n8(a);
a.V("remotePlayerChange")},zFa=function(a,b){if(-1E3!=a.ib.o){var c=1085;
switch((0,window.parseInt)(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.ib.o=c;c=(0,window.parseInt)(b.params.currentTime,10);X7(a.ib,(0,window.isNaN)(c)?0:c);a.V("remotePlayerChange")}},AFa=function(a,b){var c="true"==b.params.muted;
a.ib.volume=(0,window.parseInt)(b.params.volume,10);a.ib.muted=c;a.V("remotePlayerChange")},BFa=function(a,b){a.G=b.params.videoId;
a.V("nowAutoplaying",(0,window.parseInt)(b.params.timeout,10))},CFa=function(a,b){var c="true"==b.params.hasNext;
a.ib.mg="true"==b.params.hasPrevious;a.ib.hasNext=c;a.V("previousNextChange")},tFa=function(a){g.oE(a.K);
a.K=g.mE((0,g.B)(a.F,a,1),864E5)},o8=function(a,b,c){c?j8("Sending: action="+b+", params="+g.Ig(c)):j8("Sending: action="+b);
a.o.sendMessage(b,c)},p8=function(a){p7.call(this,"ScreenServiceProxy");
this.ld=a;this.A=[];this.A.push(this.ld.$_s("screenChange",(0,g.B)(this.FY,this)));this.A.push(this.ld.$_s("onlineScreenChange",(0,g.B)(this.JU,this)))},HFa=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.fE("MDX_CONFIG")||b;HDa();x6();q8||(q8=new h7(b?b.loungeApiHost:void 0),PDa()&&(q8.o="/api/loungedev"));r8||(r8=g.y("yt.mdx.remote.deferredProxies_")||[],g.ua("yt.mdx.remote.deferredProxies_",r8,void 0));DFa();var c=s8();if(!c){var d=new y7(q8);g.ua("yt.mdx.remote.screenService_",d,void 0);c=s8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);hFa(a,d,function(a){a?t8()&&T7(t8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){g.jG("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.y("yt.mdx.remote.initialized_")&&(g.ua("yt.mdx.remote.initialized_",!0,void 0),u8("Initializing: "+g.Ig(b)),v8.push(g.fG("yt-remote-cast2-availability-change",function(){g.jG("yt-remote-receiver-availability-change")})),v8.push(g.fG("yt-remote-cast2-receiver-selected",function(){w8(null);
g.jG("yt-remote-auto-connect","cast-selector-receiver")})),v8.push(g.fG("yt-remote-cast2-receiver-resumed",function(){g.jG("yt-remote-receiver-resumed","cast-selector-receiver")})),v8.push(g.fG("yt-remote-cast2-session-change",EFa)),v8.push(g.fG("yt-remote-connection-change",function(a){a?T7(t8(),"YouTube TV"):x8()||(T7(null,null),kFa())})),a=y8(),b.isAuto&&(a.id+="#dial"),g.jE("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),u8(" -- with channel params: "+
g.Ig(a)),FFa(a),c.start(),t8()||GFa())},JFa=function(){var a=IFa();
Q7()&&g.rH("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},IFa=function(){var a=s8().ld.$_gos();
var b=z8();b&&A8()&&(s6(a,b)||a.push(b));return GDa(a)},B8=function(){var a=KFa();
!a&&Q7()&&jFa()&&(a={key:"cast-selector-receiver",name:jFa()});return a},KFa=function(){var a=IFa(),b=z8();
b||(b=x8());return g.Ja(a,function(a){return b&&o6(b,a.key)?!0:!1})},z8=function(){var a=t8();
if(!a)return null;var b=s8().Ee();return t6(b,a)},EFa=function(a){u8("remote.onCastSessionChange_: "+p6(a));
if(a){var b=z8();b&&b.id==a.id?T7(b.id,"YouTube TV"):(b&&C8(),D8(a,1))}else A8()&&C8()},C8=function(){R7()?O7().stopSession():M7("stopSession called before API ready.");
var a=A8();a&&(a.disconnect(1),E8(null))},F8=function(){var a=A8();
return!!a&&3!=a.getProxyState()},u8=function(a){l7("remote",a)},s8=function(){if(!G8){var a=g.y("yt.mdx.remote.screenService_");
G8=a?new p8(a):null}return G8},t8=function(){return g.y("yt.mdx.remote.currentScreenId_")},LFa=function(a){g.ua("yt.mdx.remote.currentScreenId_",a,void 0)},MFa=function(){return g.y("yt.mdx.remote.connectData_")},w8=function(a){g.ua("yt.mdx.remote.connectData_",a,void 0)},A8=function(){return g.y("yt.mdx.remote.connection_")},E8=function(a){var b=A8();
w8(null);a||LFa("");g.ua("yt.mdx.remote.connection_",a,void 0);r8&&((0,g.D)(r8,function(b){b(a)}),r8.length=0);
b&&!a?g.jG("yt-remote-connection-change",!1):!b&&a&&g.jG("yt-remote-connection-change",!0)},x8=function(){var a=g.tH();
if(!a)return null;var b=s8().Ee();return t6(b,a)},D8=function(a,b){z8()&&z8();
LFa(a.id);var c=new i8(q8,a,y8());c.connect(b,MFa());c.subscribe("beforeDisconnect",function(a){g.jG("yt-remote-before-disconnect",a)});
c.subscribe("beforeDispose",function(){A8()&&E8(null)});
E8(c)},GFa=function(){var a=x8();
a?(u8("Resume connection to: "+p6(a)),D8(a,0)):(y6(),kFa(),u8("Skipping connecting because no session screen found."))},DFa=function(){var a=y8();
if(g.Zb(a)){a=w6();var b=g.rH("yt-remote-session-name")||"",c=g.rH("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.ua("yt.mdx.remote.channelParams_",a,void 0)}},y8=function(){return g.y("yt.mdx.remote.channelParams_")||{}},FFa=function(a){a?(g.qH("yt-remote-session-app",a.app),g.qH("yt-remote-session-name",a.name)):(g.sH("yt-remote-session-app"),g.sH("yt-remote-session-name"));
g.ua("yt.mdx.remote.channelParams_",a,void 0)},H8=function(a,b,c){g.L.call(this);
this.C=a;this.T=b;this.A=new g.SF(this);g.M(this,this.A);this.A.R(b,"onCaptionsTrackListChanged",this.eU);this.A.R(b,"captionschanged",this.FS);this.A.R(b,"captionssettingschanged",this.tG);this.A.R(b,"videoplayerreset",this.Jq);this.A.R(b,"mdxautoplaycancel",this.PK);this.O=this.A.R(b,"onVolumeChange",this.uE);this.G=!1;this.o=c;c.subscribe("proxyStateChange",this.KE,this);c.subscribe("remotePlayerChange",this.Ln,this);c.subscribe("remoteQueueChange",this.Jq,this);c.subscribe("autoplayUpNext",this.gE,
this);c.subscribe("previousNextChange",this.HE,this);c.subscribe("nowAutoplaying",this.yE,this);c.subscribe("autoplayDismissed",this.fE,this);this.suggestion=null;this.H=new g.TP(64);this.B=new g.U(this.pG,500,this);g.M(this,this.B);this.D=new g.U(this.qG,1E3,this);g.M(this,this.D);this.K=new G6(this.gY,0,this);g.M(this,this.K);this.F={};this.L=new g.U(this.TG,1E3,this);g.M(this,this.L);this.J=new g.ql(this.JQ,1E3,this);g.M(this,this.J);this.N=g.A;this.tG();this.Jq();this.Ln()},I8=function(a,b){var c=
a.C,d=a.T.getVideoData().lengthSeconds;
c.J=b||0;c.player.V("progresssync",b,d)},NFa=function(a){I8(a,0);
a.B.stop();J8(a,new g.TP(64))},L8=function(a,b){if(K8(a)&&!a.G){var c=null;
b&&(c={style:a.T.wj()},g.gc(c,b));a.o.eG(a.T.getVideoData(1).videoId,c);a.F=c8(a.o).A}},M8=function(a,b){var c=a.T.ug();
if(c){var d=c.Ce();var e=c.listId.toString()}var f=a.T.getVideoData(1);c=a.o;var k=f.videoId,l=d;d=f.playerParams;var m=f.Fk;f=wDa(f);var n=c8(c);l=l||0;var p={videoId:k,currentIndex:l};Z7(n,k,l);g.u(b)&&(X7(n,b),p.currentTime=b);g.u(e)&&(p.listId=e);null!=d&&(p.playerParams=d);null!=m&&(p.clickTrackingParams=m);null!=f&&(p.locationInfo=g.Ig(f));g8(c,"setPlaylist",p);e||e8(c,n);J8(a,new g.TP(1))},OFa=function(a,b){if(b){var c=a.T.Fc("captions","tracklist",{FB:1});
c&&c.length?(a.T.Xd("captions","track",b),a.G=!1):(a.T.Wk("captions"),a.G=!0)}else a.T.Xd("captions","track",{})},K8=function(a){return c8(a.o).videoId==a.T.getVideoData(1).videoId},J8=function(a,b){a.D.stop();
var c=a.H;if(!g.YP(c,b)){var d=g.W(b,2);d!=g.W(a.H,2)&&g.eU(a.T,d);a.H=b;PFa(a.C,c,b)}},N8=function(a){g.V.call(this,{I:"div",
M:"ytp-remote",P:[{I:"div",M:"ytp-remote-display-status",P:[{I:"div",M:"ytp-remote-display-status-icon",P:[g.ara()]},{I:"div",M:"ytp-remote-display-status-text",ca:"{{statustext}}"}]}]});this.B=new g.cV(this,250);g.M(this,this.B);this.C=a;this.R(a,"presentingplayerstatechange",this.D);QFa(this,g.aU(a))},QFa=function(a,b){if(3==a.C.Sa()){var c={RECEIVER_NAME:a.C.Fc("remote","currentReceiver").name};
c=g.W(b,128)?g.lX("Error on $RECEIVER_NAME",c):b.qb()||g.W(b,4)?g.lX("Playing on $RECEIVER_NAME",c):g.lX("Connected to $RECEIVER_NAME",c);a.updateValue("statustext",c);a.B.show()}else a.B.hide()},O8=function(a,b){g.BY.call(this,"Play on",0,a,b);
this.T=a;this.H={};this.R(a,"onMdxReceiversChange",this.K);this.R(a,"presentingplayerstatechange",this.K);this.K()},P8=function(a){g.FU.call(this,a);
this.A={key:r6(),name:"This computer"};this.C=null;this.D=[];this.K=this.o=null;this.H=[this.A];this.B=this.A;this.F=new g.TP(64);this.J=0;this.G=-1;if(!g.kN(g.X(this.player))){a=this.player;var b=g.iI(a);b&&(b=b.An())&&(b=new O8(a,b),g.M(this,b));b=new N8(a);g.M(this,b);g.tU(a,b.element,4)}},PFa=function(a,b,c){a.F=c;
a.player.V("presentingplayerstatechange",new g.cQ(c,b))},Q8=function(a,b){if(b.key!=a.B.key)if(b.key==a.A.key)C8();
else{a.B=b;var c=a.player.getPlaylistId();var d=a.player.getVideoData(1);var e=d.videoId;if(c||e){var f=a.player.ug();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.bc(l).videoId}else k=[e];f=a.player.getCurrentTime(1);c={videoIds:k,listId:c,videoId:e,playerParams:d.playerParams,clickTrackingParams:d.Fk,index:Math.max(a.player.KC(),0),currentTime:0==f?void 0:f};(d=wDa(d))&&(c.locationInfo=d);d=c}else d=null;u8("Connecting to: "+g.Ig(b));"cast-selector-receiver"==b.key?(w8(d||null),R7()?O7().setLaunchParams(d||
null):M7("setLaunchParams called before ready.")):!d&&F8()&&t8()==b.key?g.jG("yt-remote-connection-change",!0):(C8(),w8(d||null),d=s8().Ee(),(d=t6(d,b.key))&&D8(d,1))}},eEa={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"<"},Q6={"'":"\\'"},RFa={},CDa={UZ:"atp",E4:"ska",T3:"que",e3:"mus",A4:"sus",g1:"dsp"};
m6.prototype.Xo=function(){var a=new m6({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.B=this.B;a.A=this.A;a.o=this.o};
var z6,v6="",D6=A6("loadGamesSDK")?"/cast_game_sender.js":"/cast_sender.js",XDa=A6("loadCastFramework")||A6("loadCastApplicationFramework"),gFa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];g.C(G6,g.L);g.h=G6.prototype;g.h.LL=function(a){this.C=arguments;this.o=!1;this.Ea?this.B=(0,g.H)()+this.Dd:this.Ea=g.Dg(this.D,this.Dd)};
g.h.stop=function(){this.Ea&&(g.Eg(this.Ea),this.Ea=null);this.B=null;this.o=!1;this.C=[]};
g.h.pause=function(){++this.A};
g.h.resume=function(){this.A&&(--this.A,!this.A&&this.o&&(this.o=!1,this.F.apply(null,this.C)))};
g.h.X=function(){this.stop();G6.ea.X.call(this)};
g.h.ML=function(){this.B?(this.Ea=g.Dg(this.D,this.B-(0,g.H)()),this.B=null):(this.Ea=null,this.A?this.o=!0:(this.o=!1,this.F.apply(null,this.C)))};H6.prototype.stringify=function(a){return g.x.JSON.stringify(a,void 0)};
H6.prototype.parse=function(a){return g.x.JSON.parse(a,void 0)};g.h=I6.prototype;g.h.ej=null;g.h.Qf=!1;g.h.Ml=null;g.h.Jx=null;g.h.vl=null;g.h.wk=null;g.h.Oh=null;g.h.si=null;g.h.Dj=null;g.h.Xc=null;g.h.bo=0;g.h.Rf=null;g.h.Rr=null;g.h.Ph=null;g.h.Nm=-1;g.h.KF=!0;g.h.Oi=!1;g.h.Wt=0;g.h.Xq=null;var cEa={},L6={};g.h=I6.prototype;g.h.setTimeout=function(a){this.C=a};
g.h.eX=function(a){a=a.target;var b=this.Xq;b&&3==g.Fx(a)?b.Jm():this.eH(a)};
g.h.eH=function(a){try{if(a==this.Xc)a:{var b=g.Fx(this.Xc),c=this.Xc.A,d=this.Xc.getStatus();if(g.Id&&!g.tc(10)||g.Kd&&!g.rc("420+")){if(4>b)break a}else if(3>b||3==b&&!g.rf&&!g.Jx(this.Xc))break a;this.Oi||4!=b||7==c||(8==c||0>=d?this.o.Jf(3):this.o.Jf(2));S6(this);var e=this.Xc.getStatus();this.Nm=e;var f=g.Jx(this.Xc);(this.Qf=200==e)?(4==b&&O6(this),this.D?(dEa(this,b,f),g.rf&&this.Qf&&3==b&&(this.Z.W(this.A,"tick",this.aX),this.A.start())):N6(this,f),this.Qf&&!this.Oi&&(4==b?this.o.Hq(this):
(this.Qf=!1,K6(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.Ph=3,M6(13)):(this.Ph=0,M6(14)),O6(this),P6(this))}}catch(k){this.Xc&&g.Jx(this.Xc)}finally{}};
g.h.aX=function(){var a=g.Fx(this.Xc),b=g.Jx(this.Xc);this.bo<b.length&&(S6(this),dEa(this,a,b),this.Qf&&4!=a&&K6(this))};
g.h.mW=function(a){R6((0,g.B)(this.lW,this,a),0)};
g.h.lW=function(a){this.Oi||(S6(this),N6(this,a),K6(this))};
g.h.TE=function(a){R6((0,g.B)(this.kW,this,a),0)};
g.h.kW=function(a){this.Oi||(O6(this),this.Qf=a,this.o.Hq(this),this.o.Jf(4))};
g.h.cancel=function(){this.Oi=!0;O6(this)};
g.h.DW=function(){this.Ml=null;var a=(0,g.H)();0<=a-this.Jx?(2!=this.wk&&this.o.Jf(3),O6(this),this.Ph=2,M6(18),P6(this)):gEa(this,this.Jx-a)};g.h=jEa.prototype;g.h.Ut=null;g.h.Ke=null;g.h.Yq=!1;g.h.WA=null;g.h.np=null;g.h.Pu=null;g.h.Vt=null;g.h.ff=null;g.h.Zg=-1;g.h.Mm=null;g.h.Ul=null;g.h.connect=function(a){this.Vt=a;a=U6(this.o,null,this.Vt);M6(3);this.WA=(0,g.H)();var b=this.o.H;null!=b?(this.Mm=b[0],(this.Ul=b[1])?(this.ff=1,kEa(this)):(this.ff=2,W6(this))):(l6(a,"MODE","init"),this.Ke=new I6(this,void 0,void 0,void 0),this.Ke.ej=this.Ut,J6(this.Ke,a,!1,null,!0),this.ff=0)};
g.h.QK=function(a){if(a)this.ff=2,W6(this);else{M6(4);var b=this.o;b.ig=b.Eh.Zg;c7(b,9)}a&&this.Jf(2)};
g.h.jt=function(a){return this.o.jt(a)};
g.h.abort=function(){this.Ke&&(this.Ke.cancel(),this.Ke=null);this.Zg=-1};
g.h.VA=function(){return!1};
g.h.LE=function(a,b){this.Zg=a.Nm;if(0==this.ff)if(b){try{var c=this.A.parse(b)}catch(d){c=this.o;c.ig=this.Zg;c7(c,2);return}this.Mm=c[0];this.Ul=c[1]}else c=this.o,c.ig=this.Zg,c7(c,2);else if(2==this.ff)if(this.Yq)M6(7),this.Pu=(0,g.H)();else if("11111"==b){if(M6(6),this.Yq=!0,this.np=(0,g.H)(),c=this.np-this.WA,!g.Id||g.tc(10)||500>c)this.Zg=200,this.Ke.cancel(),M6(12),V6(this.o,this,!0)}else M6(8),this.np=this.Pu=(0,g.H)(),this.Yq=!1};
g.h.Hq=function(){this.Zg=this.Ke.Nm;if(this.Ke.Qf)0==this.ff?this.Ul?(this.ff=1,kEa(this)):(this.ff=2,W6(this)):2==this.ff&&((!g.Id||g.tc(10)?!this.Yq:200>this.Pu-this.np)?(M6(11),V6(this.o,this,!1)):(M6(12),V6(this.o,this,!0)));else{0==this.ff?M6(9):2==this.ff&&M6(10);var a=this.o;a.ig=this.Zg;c7(a,2)}};
g.h.Un=function(){return this.o.Un()};
g.h.isActive=function(){return this.o.isActive()};
g.h.Jf=function(a){this.o.Jf(a)};g.h=X6.prototype;g.h.sm=null;g.h.ke=null;g.h.Ac=null;g.h.Tt=null;g.h.tp=null;g.h.rz=null;g.h.Gp=null;g.h.Gn=0;g.h.YR=0;g.h.Cd=null;g.h.Jh=null;g.h.Lg=null;g.h.Ri=null;g.h.Eh=null;g.h.Pr=null;g.h.Mk=-1;g.h.TB=-1;g.h.ig=-1;g.h.kk=0;g.h.Yj=0;g.h.Qi=8;var d7=new g.Qf;g.C(mEa,g.pf);g.C(nEa,g.pf);g.C(oEa,g.pf);g.h=X6.prototype;g.h.connect=function(a,b,c,d,e){M6(0);this.Tt=b;this.sm=c||{};d&&g.u(e)&&(this.sm.OSID=d,this.sm.OAID=e);this.F?(R6((0,g.B)(this.Oz,this,a),100),sEa(this)):this.Oz(a)};
g.h.Oz=function(a){this.Eh=new jEa(this);this.Eh.Ut=null;this.Eh.A=this.D;this.Eh.connect(a)};
g.h.VA=function(){return 0==this.o};
g.h.RE=function(a){this.Jh=null;vEa(this,a)};
g.h.QE=function(){this.Lg=null;this.Ac=new I6(this,this.B,"rpc",this.G);this.Ac.ej=null;this.Ac.Wt=0;var a=this.rz.clone();g.Zm(a,"RID","rpc");g.Zm(a,"SID",this.B);g.Zm(a,"CI",this.Pr?"0":"1");g.Zm(a,"AID",this.Mk);Y6(this,a);if(!g.Id||g.tc(10))g.Zm(a,"TYPE","xmlhttp"),J6(this.Ac,a,!0,this.Gp,!1);else{g.Zm(a,"TYPE","html");var b=this.Ac,c=!!this.Gp;b.wk=3;b.Oh=k6(a.clone());fEa(b,c)}};
g.h.LE=function(a,b){if(0!=this.o&&(this.Ac==a||this.ke==a))if(this.ig=a.Nm,this.ke==a&&3==this.o)if(7<this.Qi){try{var c=this.D.parse(b)}catch(f){c=null}if(g.xa(c)&&3==c.length)if(0==c[0])a:{if(!this.Lg){if(this.Ac)if(this.Ac.vl+3E3<this.ke.vl)$6(this),this.Ac.cancel(),this.Ac=null;else break a;b7(this);M6(19)}}else this.TB=c[1],0<this.TB-this.Mk&&37500>c[2]&&this.Pr&&0==this.Yj&&!this.Ri&&(this.Ri=R6((0,g.B)(this.AS,this),6E3));else c7(this,11)}else b!=RFa.X_.o&&c7(this,11);else if(this.Ac==a&&
$6(this),!g.F(b)){c=this.D.parse(b);g.xa(c);for(var d=0;d<c.length;d++){var e=c[d];this.Mk=e[0];e=e[1];2==this.o?"c"==e[0]?(this.B=e[1],this.Gp=e[2],e=e[3],null!=e?this.Qi=e:this.Qi=6,this.o=3,this.Cd&&this.Cd.Fz(),this.rz=U6(this,this.Un()?this.Gp:null,this.Tt),wEa(this)):"stop"==e[0]&&c7(this,7):3==this.o&&("stop"==e[0]?c7(this,7):"noop"!=e[0]&&this.Cd&&this.Cd.Ez(e),this.Yj=0)}}};
g.h.AS=function(){null!=this.Ri&&(this.Ri=null,this.Ac.cancel(),this.Ac=null,b7(this),M6(20))};
g.h.Hq=function(a){if(this.Ac==a){$6(this);this.Ac=null;var b=2}else if(this.ke==a)this.ke=null,b=1;else return;this.ig=a.Nm;if(0!=this.o)if(a.Qf)1==b?(b=(0,g.H)()-a.vl,d7.dispatchEvent(new nEa(d7,a.Dj?a.Dj.length:0,b,this.kk)),Z6(this),this.C.length=0):wEa(this);else{var c=a.Ph,d;if(!(d=3==c||7==c||0==c&&0<this.ig)){if(d=1==b)this.ke||this.Jh||1==this.o||2<=this.kk?d=!1:(this.Jh=R6((0,g.B)(this.RE,this,a),xEa(this,this.kk)),this.kk++,d=!0);d=!(d||2==b&&b7(this))}if(d)switch(c){case 1:c7(this,5);
break;case 4:c7(this,10);break;case 3:c7(this,6);break;case 7:c7(this,12);break;default:c7(this,2)}}};
g.h.mL=function(a){if(!g.Na(arguments,this.o))throw Error("Unexpected channel state: "+this.o);};
g.h.SX=function(a){a?M6(2):(M6(1),yEa(this,8))};
g.h.jt=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new g.zx;a.H=!1;return a};
g.h.isActive=function(){return!!this.Cd&&this.Cd.isActive(this)};
g.h.Jf=function(a){d7.dispatchEvent(new oEa(d7,a))};
g.h.Un=function(){return!(!g.Id||g.tc(10))};
g.h=zEa.prototype;g.h.Fz=function(){};
g.h.Ez=function(){};
g.h.Dz=function(){};
g.h.Qs=function(){};
g.h.CA=function(){return{}};
g.h.isActive=function(){return!0};g.C(e7,g.L);g.h=e7.prototype;g.h.dW=function(){this.Dd=Math.min(3E5,2*this.Dd);this.B();this.A&&this.start()};
g.h.start=function(){var a=this.Dd+15E3*Math.random();g.yu(this.o,a);this.A=(0,g.H)()+a};
g.h.stop=function(){this.o.stop();this.A=0};
g.h.isActive=function(){return this.o.isActive()};
g.h.reset=function(){this.o.stop();this.Dd=5E3};g.C(f7,zEa);g.h=f7.prototype;g.h.subscribe=function(a,b,c){return this.B.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.B.unsubscribe(a,b,c)};
g.h.ce=function(a){return this.B.ce(a)};
g.h.V=function(a,b){return this.B.V.apply(this.B,arguments)};
g.h.dispose=function(){this.K||(this.K=!0,g.mf(this.B),CEa(this),g.mf(this.A),this.A=null)};
g.h.la=function(){return this.K};
g.h.connect=function(a,b,c){if(!this.o||2!=this.o.o){this.J="";this.A.stop();this.D=a||null;this.C=b||0;a=this.L+"/test";b=this.L+"/bind";var d=new X6(c?c.firstTestResults:null,c?c.secondTestResults:null,this.N),e=this.o;e&&(e.Cd=null);d.Cd=this;this.o=d;e?this.o.connect(a,b,this.F,e.B,e.Mk):c?this.o.connect(a,b,this.F,c.sessionId,c.arrayId):this.o.connect(a,b,this.F)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.gc(c,b);this.A.isActive()||2==(this.o?this.o.o:0)?this.G.push(c):g7(this)&&tEa(this.o,c)};
g.h.Fz=function(){this.A.reset();this.D=null;this.C=0;if(this.G.length){var a=this.G;this.G=[];for(var b=0,c=a.length;b<c;++b)tEa(this.o,a[b])}this.V("handlerOpened")};
g.h.Dz=function(a){var b=2==a&&401==this.o.ig;4==a||b||this.A.start();this.V("handlerError",a)};
g.h.Qs=function(a){if(!this.A.isActive())this.V("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.G.push(d)}};
g.h.CA=function(){var a={v:2};this.J&&(a.gsessionid=this.J);0!=this.C&&(a.ui=""+this.C);0!=this.H&&(a.ui=""+this.H);this.D&&g.gc(a,this.D);return a};
g.h.Ez=function(a){"S"==a[0]?this.J=a[1]:"gracefulReconnect"==a[0]?(this.A.start(),rEa(this.o)):this.V("handlerMessage",new AEa(a[0],a[1]))};
g.h.BY=function(){this.A.isActive();var a=this.o,b=0;a.Ac&&b++;a.ke&&b++;0!=b||this.connect(this.D,this.C)};h7.prototype.C=function(a,b,c,d){b?a(d):a({text:c.responseText})};
h7.prototype.B=function(a,b){a(Error("Request error: "+b.status))};
h7.prototype.D=function(a){a(Error("request timed out"))};var KEa=(0,g.H)(),k7=null,n7=Array(50),m7=-1,o7=!1;g.C(p7,g.VF);p7.prototype.Ee=function(){return this.o};
p7.prototype.contains=function(a){return!!s6(this.o,a)};
p7.prototype.get=function(a){return a?t6(this.o,a):null};
p7.prototype.info=function(a){l7(this.G,a)};g.C(q7,g.VF);var SFa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.h=q7.prototype;g.h.start=function(){!this.o&&(0,window.isNaN)(this.Ea)&&this.jH()};
g.h.stop=function(){this.o&&(this.o.abort(),this.o=null);(0,window.isNaN)(this.Ea)||(g.oE(this.Ea),this.Ea=window.NaN)};
g.h.X=function(){this.stop();q7.ea.X.call(this)};
g.h.jH=function(){this.Ea=window.NaN;this.o=g.DE(i7(this.F,"/pairing/get_screen"),{method:"POST",Rb:{pairing_code:this.D},timeout:5E3,onSuccess:(0,g.B)(this.DY,this),onError:(0,g.B)(this.CY,this),Hd:(0,g.B)(this.EY,this)})};
g.h.DY=function(a,b){this.o=null;var c=b.screen||{};c.dialId=this.B;c.name=this.C;this.V("pairingComplete",new n6(c))};
g.h.CY=function(a){this.o=null;a.status&&404==a.status?this.A>=SFa.length?this.V("pairingFailed",Error("DIAL polling timed out")):(a=SFa[this.A],this.Ea=g.mE((0,g.B)(this.jH,this),a),this.A++):this.V("pairingFailed",Error("Server error "+a.status))};
g.h.EY=function(){this.o=null;this.V("pairingFailed",Error("Server not responding"))};g.C(s7,p7);g.h=s7.prototype;g.h.start=function(){r7(this)&&this.V("screenChange");!g.rH("yt-remote-lounge-token-expiration")&&OEa(this);g.oE(this.A);this.A=g.mE((0,g.B)(this.start,this),1E4)};
g.h.add=function(a,b){r7(this);LEa(this,a);t7(this,!1);this.V("screenChange");b(a);a.token||OEa(this)};
g.h.remove=function(a,b){var c=r7(this);NEa(this,a)&&(t7(this,!1),c=!0);b(a);c&&this.V("screenChange")};
g.h.Kr=function(a,b,c,d){var e=r7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,t7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.V("screenChange")};
g.h.X=function(){g.oE(this.A);s7.ea.X.call(this)};
g.h.ZL=function(a){r7(this);var b=this.o.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}t7(this,!b);b&&l7(this.G,"Missed "+b+" lounge tokens.")};
g.h.YL=function(a){l7(this.G,"Requesting lounge tokens failed: "+a)};g.C(v7,g.VF);g.h=v7.prototype;g.h.start=function(){var a=(0,window.parseInt)(g.rH("yt-remote-fast-check-period")||"0",10);(this.C=(0,g.H)()-144E5<a?0:a)?x7(this):(this.C=(0,g.H)()+3E5,g.qH("yt-remote-fast-check-period",this.C),this.Mw())};
g.h.isEmpty=function(){return g.Zb(this.o)};
g.h.update=function(){u7("Updating availability on schedule.");var a=this.F(),b=g.Jb(this.o,function(b,d){return b&&!!t6(a,d)},this);
w7(this,b)};
g.h.X=function(){g.oE(this.B);this.B=window.NaN;this.A&&(this.A.abort(),this.A=null);v7.ea.X.call(this)};
g.h.Mw=function(){g.oE(this.B);this.B=window.NaN;this.A&&this.A.abort();var a=REa(this);if(g.Ob(a)){var b=i7(this.D,"/pairing/get_screen_availability");this.A=j7(this.D,b,{lounge_token:g.Rb(a).join(",")},(0,g.B)(this.LV,this,a),(0,g.B)(this.KV,this))}else w7(this,{}),x7(this)};
g.h.LV=function(a,b){this.A=null;var c=g.Rb(REa(this));if(g.gb(c,g.Rb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;w7(this,d);x7(this)}else this.sc("Changing Screen set during request."),this.Mw()};
g.h.KV=function(a){this.sc("Screen availability failed: "+a);this.A=null;x7(this)};
g.h.sc=function(a){l7("OnlineScreenService",a)};g.C(y7,p7);g.h=y7.prototype;g.h.start=function(){this.B.start();this.A.start();this.o.length&&(this.V("screenChange"),this.A.isEmpty()||this.V("onlineScreenChange"))};
g.h.add=function(a,b,c){this.B.add(a,b,c)};
g.h.remove=function(a,b,c){this.B.remove(a,b,c);this.A.update()};
g.h.Kr=function(a,b,c,d){this.B.contains(a)?this.B.Kr(a,b,c,d):(a="Updating name of unknown screen: "+a.name,l7(this.G,a),d(Error(a)))};
g.h.Ee=function(a){return a?this.o:g.Va(this.o,(0,g.Wd)(this.C,function(a){return!this.contains(a)},this))};
g.h.kH=function(){return(0,g.Wd)(this.Ee(!0),function(a){return!!this.A.o[a.id]},this)};
g.h.lH=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new q7(this.F,a,b,c);f.subscribe("pairingComplete",(0,g.B)(function(a){g.mf(f);d(z7(this,a))},this));
f.subscribe("pairingFailed",function(a){g.mf(f);e(a)});
f.start();return(0,g.B)(f.stop,f)};
g.h.GY=function(a,b,c,d){g.DE(i7(this.F,"/pairing/get_screen"),{method:"POST",Rb:{pairing_code:a},timeout:5E3,onSuccess:(0,g.B)(function(a,d){var e=new n6(d.screen||{});if(!e.name||VEa(this,e.name)){a:{var f=e.name;for(var m=2,n=b(f,m);VEa(this,n);){m++;if(20<m)break a;n=b(f,m)}f=n}e.name=f}c(z7(this,e))},this),
onError:(0,g.B)(function(a){d(Error("pairing request failed: "+a.status))},this),
Hd:(0,g.B)(function(){d(Error("pairing request timed out."))},this)})};
g.h.X=function(){g.mf(this.B);g.mf(this.A);y7.ea.X.call(this)};
g.h.nM=function(){WEa(this);this.V("screenChange");this.A.update()};
y7.prototype.dispose=y7.prototype.dispose;g.C(B7,g.VF);g.h=B7.prototype;g.h.Iq=function(a){this.B=a;this.V("sessionScreen",this.B)};
g.h.Je=function(a){this.la()||(a&&C7(this,""+a),this.B=null,this.V("sessionScreen",null))};
g.h.info=function(a){l7(this.N,a)};
g.h.nH=function(){return null};
g.h.Uw=function(a){var b=this.A;a?(b.displayStatus=new window.chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;window.chrome.cast.setReceiverDisplayStatus(b,(0,g.B)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.B)(function(){C7(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.X=function(){this.Uw("");B7.ea.X.call(this)};g.C(D7,B7);g.h=D7.prototype;g.h.Tw=function(a){if(this.o){if(this.o==a)return;C7(this,"Overriding cast sesison with new session object");this.o.removeUpdateListener(this.F);this.o.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.D)}this.o=a;this.o.addUpdateListener(this.F);this.o.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.D);YEa(this)};
g.h.Ok=function(a){this.info("launchWithParams no-op for Cast: "+g.Ig(a))};
g.h.stop=function(){this.o?this.o.stop((0,g.B)(function(){this.Je()},this),(0,g.B)(function(){this.Je(Error("Failed to stop receiver app."))},this)):this.Je(Error("Stopping cast device witout session."))};
g.h.Uw=g.A;g.h.X=function(){this.info("disposeInternal");g.oE(this.C);this.C=0;this.o&&(this.o.removeUpdateListener(this.F),this.o.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.D));this.o=null;D7.ea.X.call(this)};
g.h.PW=function(a,b){if(!this.la())if(b){var c=g.tx(b);if(g.Aa(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.Ig(c));switch(d){case "mdxSessionStatus":XEa(this,c.screenId);break;default:C7(this,"Unknown youtube message: "+d)}}else C7(this,"Unable to parse message.")}else C7(this,"No data in message.")};
g.h.LA=function(a,b,c,d){UEa(this.J,this.A.label,a,this.A.friendlyName,(0,g.B)(function(e){e?b(e):0<=d?(C7(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.mE((0,g.B)(this.LA,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.nH=function(){return this.o};
g.h.HY=function(a){this.la()||a||(C7(this,"Cast session died."),this.Je())};g.C(E7,B7);g.h=E7.prototype;g.h.Tw=function(a){this.C=a;this.C.addUpdateListener(this.L)};
g.h.Ok=function(a){this.D=a;this.G()};
g.h.stop=function(){this.o();this.o=g.A;g.oE(this.F);this.C?this.C.stop((0,g.B)(this.Je,this,null),(0,g.B)(this.Je,this,"Failed to stop DIAL device.")):this.Je()};
g.h.X=function(){this.o();this.o=g.A;g.oE(this.F);this.C&&this.C.removeUpdateListener(this.L);this.C=null;E7.ea.X.call(this)};
g.h.KY=function(a){this.la()||a||(C7(this,"DIAL session died."),this.o(),this.o=g.A,this.Je())};
g.h.Au=function(a){this.K=r6();if(this.D){var b=new window.chrome.cast.DialLaunchResponse(!0,$Ea(this));a(b);ZEa(this)}else this.G=(0,g.B)(function(){g.oE(this.F);this.G=g.A;this.F=window.NaN;var b=new window.chrome.cast.DialLaunchResponse(!0,$Ea(this));a(b);ZEa(this)},this),this.F=g.mE((0,g.B)(function(){this.G()},this),100)};
g.h.CN=function(a,b,c){UEa(this.J,this.H.receiver.label,a,this.A.friendlyName,(0,g.B)(function(a){a&&a.token?(this.Iq(a),b(new window.chrome.cast.DialLaunchResponse(!1))):this.Au(b,c)},this),(0,g.B)(function(a){C7(this,"Failed to get DIAL screen: "+a);
this.Au(b,c)},this))};g.C(F7,B7);F7.prototype.stop=function(){this.Je()};
F7.prototype.Tw=g.A;F7.prototype.Ok=function(){g.oE(this.o);this.o=window.NaN;var a=t6(this.J.Ee(),this.A.label);a?this.Iq(a):this.Je(Error("No such screen"))};
F7.prototype.X=function(){g.oE(this.o);this.o=window.NaN;F7.ea.X.call(this)};g.C(G7,g.VF);g.h=G7.prototype;
g.h.init=function(a,b){window.chrome.cast.timeout.requestSession=3E4;var c=new window.chrome.cast.SessionRequest(this.G);this.H||(c.dialRequest=new window.chrome.cast.DialRequest("YouTube"));var d=window.chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?window.chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:window.chrome.cast.DefaultActionPolicy.CREATE_SESSION;c=new window.chrome.cast.ApiConfig(c,(0,g.B)(this.NE,this),(0,g.B)(this.sV,this),d,e);c.customDialLaunchCallback=(0,g.B)(this.lT,this);window.chrome.cast.initialize(c,
(0,g.B)(function(){this.la()||(window.chrome.cast.addReceiverActionListener(this.C),HEa(),this.A.subscribe("onlineScreenChange",(0,g.B)(this.mH,this)),this.B=bFa(this),window.chrome.cast.setCustomReceivers(this.B,g.A,(0,g.B)(function(a){this.sc("Failed to set initial custom receivers: "+g.Ig(a))},this)),this.V("yt-remote-cast2-availability-change",I7(this)),b(!0))},this),(0,g.B)(function(a){this.sc("Failed to initialize API: "+g.Ig(a));
b(!1)},this))};
g.h.AX=function(a,b){H7("Setting connected screen ID: "+a+" -> "+b);if(this.o){var c=this.o.B;if(!a||c&&c.id!=a)H7("Unsetting old screen status: "+this.o.A.friendlyName),J7(this,null)}if(a&&b){if(!this.o){c=t6(this.A.Ee(),a);if(!c){H7("setConnectedScreenStatus: Unknown screen.");return}var d=aFa(this,c);d||(H7("setConnectedScreenStatus: Connected receiver not custom..."),d=new window.chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM,this.B.push(d),
window.chrome.cast.setCustomReceivers(this.B,g.A,(0,g.B)(function(a){this.sc("Failed to set initial custom receivers: "+g.Ig(a))},this)));
H7("setConnectedScreenStatus: new active receiver: "+d.friendlyName);J7(this,new F7(this.A,d),!0)}this.o.Uw(b)}else H7("setConnectedScreenStatus: no screen.")};
g.h.BX=function(a){this.la()?this.sc("Setting connection data on disposed cast v2"):this.o?this.o.Ok(a):this.sc("Setting connection data without a session")};
g.h.JY=function(){this.la()?this.sc("Stopping session on disposed cast v2"):this.o?(this.o.stop(),J7(this,null)):H7("Stopping non-existing session")};
g.h.requestSession=function(){window.chrome.cast.requestSession((0,g.B)(this.NE,this),(0,g.B)(this.PV,this))};
g.h.X=function(){this.A.unsubscribe("onlineScreenChange",(0,g.B)(this.mH,this));window.chrome&&window.chrome.cast&&window.chrome.cast.removeReceiverActionListener(this.C);g.Sa(g.y("yt.mdx.remote.debug.handlers_")||[],EEa);g.mf(this.o);G7.ea.X.call(this)};
g.h.sc=function(a){l7("Controller",a)};
g.h.OE=function(a,b){this.o==a&&(b||J7(this,null),this.V("yt-remote-cast2-session-change",b))};
g.h.oV=function(a,b){if(!this.la())if(a)switch(a.friendlyName=window.chrome.cast.unescape(a.friendlyName),H7("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case window.chrome.cast.ReceiverAction.CAST:if(this.o)if(this.o.A.label!=a.label)H7("onReceiverAction_: Stopping active receiver: "+this.o.A.friendlyName),this.o.stop();else{H7("onReceiverAction_: Casting to active receiver.");this.o.B&&this.V("yt-remote-cast2-session-change",this.o.B);break}switch(a.receiverType){case window.chrome.cast.ReceiverType.CUSTOM:J7(this,
new F7(this.A,a));break;case window.chrome.cast.ReceiverType.DIAL:J7(this,new E7(this.A,a,this.F));break;case window.chrome.cast.ReceiverType.CAST:J7(this,new D7(this.A,a));break;default:this.sc("Unknown receiver type: "+a.receiverType)}break;case window.chrome.cast.ReceiverAction.STOP:this.o&&this.o.A.label==a.label?this.o.stop():this.sc("Stopping receiver w/o session: "+a.friendlyName)}else this.sc("onReceiverAction_ called without receiver.")};
g.h.lT=function(a){if(this.la())return window.Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=window.chrome.cast.ReceiverType.DIAL&&(this.sc("Not DIAL receiver: "+b.friendlyName),b.receiverType=window.chrome.cast.ReceiverType.DIAL);var c=this.o?this.o.A:null;if(!c||c.label!=b.label)return this.sc("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),window.Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=window.chrome.cast.ReceiverType.DIAL){if(this.o.B)return H7("Reselecting dial screen."),
this.V("yt-remote-cast2-session-change",this.o.B),window.Promise.resolve(new window.chrome.cast.DialLaunchResponse(!1));this.sc('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);J7(this,new E7(this.A,b,this.F))}b=this.o;b.H=a;return b.H.appState==window.chrome.cast.DialAppState.RUNNING?new window.Promise((0,g.B)(b.CN,b,(b.H.extraData||{}).screenId||null)):new window.Promise((0,g.B)(b.Au,b))};
g.h.NE=function(a){if(!this.la()){H7("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=window.chrome.cast.ReceiverType.CUSTOM){if(!this.o)if(b.receiverType==window.chrome.cast.ReceiverType.CAST)H7("Got resumed cast session before resumed mdx connection."),b.friendlyName=window.chrome.cast.unescape(b.friendlyName),J7(this,new D7(this.A,b),!0);else{this.sc("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.o.A,d=t6(this.A.Ee(),c.label);
d&&o6(d,b.label)&&c.receiverType!=window.chrome.cast.ReceiverType.CAST&&b.receiverType==window.chrome.cast.ReceiverType.CAST&&(H7("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.mf(this.o),this.o=new D7(this.A,b),this.o.subscribe("sessionScreen",(0,g.B)(this.OE,this,this.o)),this.o.Ok(null));this.o.Tw(a)}}};
g.h.IY=function(){return this.o?this.o.nH():null};
g.h.PV=function(a){this.la()||(this.sc("Failed to estabilish a session: "+g.Ig(a)),a.code!=window.chrome.cast.ErrorCode.CANCEL&&J7(this,null))};
g.h.sV=function(a){H7("Receiver availability updated: "+a);if(!this.la()){var b=I7(this);this.D=a==window.chrome.cast.ReceiverAvailability.AVAILABLE;I7(this)!=b&&this.V("yt-remote-cast2-availability-change",I7(this))}};
g.h.mH=function(){this.la()||(this.B=bFa(this),H7("Updating custom receivers: "+g.Ig(this.B)),window.chrome.cast.setCustomReceivers(this.B,g.A,(0,g.B)(function(){this.sc("Failed to set custom receivers.")},this)),this.V("yt-remote-cast2-availability-change",I7(this)))};
G7.prototype.setLaunchParams=G7.prototype.BX;G7.prototype.setConnectedScreenStatus=G7.prototype.AX;G7.prototype.stopSession=G7.prototype.JY;G7.prototype.getCastSession=G7.prototype.IY;G7.prototype.requestSession=G7.prototype.requestSession;G7.prototype.init=G7.prototype.init;G7.prototype.dispose=G7.prototype.dispose;var P7=[];g.h=U7.prototype;
g.h.reset=function(a){this.listId="";this.index=-1;this.videoId="";V7(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.o=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.A=a.trackData,this.mg=a.hasPrevious,this.hasNext=a.hasNext,this.H=a.playerTime,this.G=a.playerTimeAt,this.D=a.seekableStart,this.B=a.seekableEnd,this.J=a.duration,this.K=a.loadedTime,this.C=a.liveIngestionTime,this.F=!(0,window.isNaN)(this.C))};
g.h.qb=function(){return 1==this.o};
g.h.isAdPlaying=function(){return 1081==this.o};
g.h.getDuration=function(){return this.F?this.J+W7(this):this.J};
g.h.clone=function(){return new U7($7(this))};g.C(b8,g.VF);g.h=b8.prototype;g.h.play=function(){1==this.o?(this.A?this.A.play(null,g.A,h8(this,"play")):g8(this,"play"),f8(this,1,Y7(c8(this))),this.V("remotePlayerChange")):d8(this,this.play)};
g.h.pause=function(){1==this.o?(this.A?this.A.pause(null,g.A,h8(this,"pause")):g8(this,"pause"),f8(this,2,Y7(c8(this))),this.V("remotePlayerChange")):d8(this,this.pause)};
g.h.iH=function(a){if(1==this.o){if(this.A){var b=c8(this),c=new window.chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=b.qb()||3==b.o?window.chrome.cast.media.ResumeState.PLAYBACK_START:window.chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.A.seek(c,g.A,h8(this,"seekTo",{newTime:a}))}else g8(this,"seekTo",{newTime:a});f8(this,3,a);this.V("remotePlayerChange")}else d8(this,g.Da(this.iH,a))};
g.h.stop=function(){if(1==this.o){this.A?this.A.stop(null,g.A,h8(this,"stopVideo")):g8(this,"stopVideo");var a=c8(this);a.index=-1;a.videoId="";V7(a);e8(this,a);this.V("remotePlayerChange")}else d8(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.o){var c=c8(this);if(this.B){if(c.volume!=a){var d=Math.round(a)/100;this.B.setReceiverVolumeLevel(d,(0,g.B)(function(){l7("CP","set receiver volume: "+d)},this),(0,g.B)(function(){this.sc("failed to set receiver volume.")},this))}c.muted!=b&&this.B.setReceiverMuted(b,(0,g.B)(function(){l7("CP","set receiver muted: "+b)},this),(0,g.B)(function(){this.sc("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);g8(this,"setVolume",e)}c.muted=b;c.volume=a;e8(this,c)}else d8(this,g.Da(this.setVolume,a,b))};
g.h.eG=function(a,b){if(1==this.o){var c=c8(this),d={videoId:a};b&&(c.A={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,format:b.format,kind:b.kind},d.style=g.Ig(b.style),g.gc(d,c.A));g8(this,"setSubtitlesTrack",d);e8(this,c)}else d8(this,g.Da(this.eG,a,b))};
g.h.Px=function(a,b){if(1==this.o){g8(this,"setAudioTrack",{videoId:a,audioTrackId:b.Kb.id});var c=c8(this);c.audioTrackId=b.Kb.id;e8(this,c)}else d8(this,g.Da(this.Px,a,b))};
g.h.hH=function(a,b){if(1==this.o){if(a&&b){var c=c8(this);Z7(c,a,b);e8(this,c)}g8(this,"previous")}else d8(this,g.Da(this.hH,a,b))};
g.h.gH=function(a,b){if(1==this.o){if(a&&b){var c=c8(this);Z7(c,a,b);e8(this,c)}g8(this,"next")}else d8(this,g.Da(this.gH,a,b))};
g.h.gA=function(){1==this.o?g8(this,"dismissAutoplay"):d8(this,this.gA)};
g.h.dispose=function(){if(3!=this.o){var a=this.o;this.o=3;this.V("proxyStateChange",a,this.o)}b8.ea.dispose.call(this)};
g.h.X=function(){oFa(this);this.C=null;this.D.clear();a8(this,null);b8.ea.X.call(this)};
g.h.Qx=function(a){if((a!=this.o||2==a)&&3!=this.o&&0!=a){var b=this.o;this.o=a;this.V("proxyStateChange",b,a);if(1==a)for(;!this.D.isEmpty();)g.NC(this.D).apply(this);else 3==a&&this.dispose()}};
g.h.jV=function(a,b){this.V(a,b)};
g.h.HS=function(a){if(!a)this.Jn(null),a8(this,null);else if(this.B.receiver.volume){a=this.B.receiver.volume;var b=c8(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)l7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,e8(this,b)}};
g.h.Jn=function(a){l7("CP","Cast media: "+!!a);this.A&&this.A.removeUpdateListener(this.H);if(this.A=a)this.A.addUpdateListener(this.H),pFa(this),this.V("remotePlayerChange")};
g.h.GS=function(a){a?(pFa(this),this.V("remotePlayerChange")):this.Jn(null)};
g.h.US=function(){var a=lFa();a&&a8(this,a)};
g.h.sc=function(a){l7("CP",a)};g.C(i8,g.VF);g.h=i8.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;g.u(m)&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);g.u(k)&&(l.currentIndex=k);c&&(this.ib.listId=c);this.ib.videoId=d;this.ib.index=k||0;this.ib.state=3;X7(this.ib,m);this.C="UNSUPPORTED";j8("Connecting with setPlaylist and params: "+g.Ig(l));this.o.connect({method:"setPlaylist",
params:g.Ig(l)},a,KDa())}else j8("Connecting without params"),this.o.connect({},a,KDa());rFa(this)};
g.h.dispose=function(){this.la()||(this.V("beforeDispose"),k8(this,3));i8.ea.dispose.call(this)};
g.h.X=function(){l8(this);n8(this);m8(this);g.oE(this.J);this.J=window.NaN;g.oE(this.K);this.K=window.NaN;this.B=null;g.FF(this.Y);this.Y.length=0;this.o.dispose();i8.ea.X.call(this);this.C=this.G=this.A=this.ib=this.o=null};
g.h.QL=function(){this.F(2)};
g.h.LS=function(){j8("Channel opened");this.O&&(this.O=!1,m8(this),this.N=g.mE((0,g.B)(function(){j8("Timing out waiting for a screen.");this.F(1)},this),15E3));
ODa(BEa(this.o),this.da)};
g.h.IS=function(){j8("Channel closed");(0,window.isNaN)(this.D)?y6(!0):y6();this.dispose()};
g.h.JS=function(a){y6();(0,window.isNaN)(this.H())?(j8("Channel error: "+a+" without reconnection"),this.dispose()):(this.O=!0,j8("Channel error: "+a+" with reconnection in "+this.H()+" ms"),k8(this,2))};
g.h.KS=function(a){a.params?j8("Received: action="+a.action+", params="+g.Ig(a.params)):j8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=g.tx(a.params.devices);this.A=(0,g.I)(a,function(a){return new m6(a)});
a=!!g.Ja(this.A,function(a){return"LOUNGE_SCREEN"==a.type});
uFa(this,a);break;case "loungeScreenDisconnected":g.Ta(this.A,function(a){return"LOUNGE_SCREEN"==a.type});
uFa(this,!1);break;case "remoteConnected":var b=new m6(g.tx(a.params.device));g.Ja(this.A,function(a){return b?a.id==b.id:!1})||g.Qa(this.A,b);
break;case "remoteDisconnected":b=new m6(g.tx(a.params.device));g.Ta(this.A,function(a){return b?a.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":wFa(this,a);break;case "nowPlaying":yFa(this,a);break;case "onStateChange":xFa(this,a);break;case "onAdStateChange":zFa(this,a);break;case "onVolumeChanged":AFa(this,a);break;case "onSubtitlesTrackChanged":vFa(this,a);break;case "nowAutoplaying":BFa(this,a);break;case "autoplayDismissed":this.V("autoplayDismissed");break;case "autoplayUpNext":this.G=a.params.videoId||null;this.V("autoplayUpNext",this.G);break;case "onAutoplayModeChanged":this.C=
a.params.autoplayMode;this.V("autoplayModeChange",this.C);"DISABLED"==this.C&&this.V("autoplayDismissed");break;case "onHasPreviousNextChanged":CFa(this,a);break;case "requestAssistedSignIn":this.V("assistedSignInRequested",a.params.authCode);break;default:j8("Unrecognized action: "+a.action)}};
g.h.mX=function(){if(this.B){var a=this.B;this.B=null;this.ib.videoId!=a&&o8(this,"getNowPlaying")}};
i8.prototype.subscribe=i8.prototype.subscribe;i8.prototype.unsubscribeByKey=i8.prototype.ce;i8.prototype.ka=function(){var a=3;this.la()||(a=0,(0,window.isNaN)(this.H())?g7(this.o)&&(0,window.isNaN)(this.D)&&(a=1):a=2);return a};
i8.prototype.getProxyState=i8.prototype.ka;i8.prototype.F=function(a){j8("Disconnecting with "+a);l8(this);this.V("beforeDisconnect",a);1==a&&y6();CEa(this.o,a);this.dispose()};
i8.prototype.disconnect=i8.prototype.F;i8.prototype.ha=function(){var a=this.ib;this.B&&(a=this.ib.clone(),Z7(a,this.B,a.index));return $7(a)};
i8.prototype.getPlayerContextData=i8.prototype.ha;
i8.prototype.pa=function(a){var b=new U7(a);b.videoId&&b.videoId!=this.ib.videoId&&(this.B=b.videoId,g.oE(this.J),this.J=g.mE((0,g.B)(this.mX,this),5E3));var c=[];this.ib.listId==b.listId&&this.ib.videoId==b.videoId&&this.ib.index==b.index||c.push("remoteQueueChange");this.ib.o==b.o&&this.ib.volume==b.volume&&this.ib.muted==b.muted&&Y7(this.ib)==Y7(b)&&g.Ig(this.ib.A)==g.Ig(b.A)||c.push("remotePlayerChange");this.ib.reset(a);(0,g.D)(c,function(a){this.V(a)},this)};
i8.prototype.setPlayerContextData=i8.prototype.pa;i8.prototype.aa=function(){var a=this.o.F.id,b=g.Ja(this.A,function(b){return"REMOTE_CONTROL"==b.type&&b.id!=a});
return b?b.id:""};
i8.prototype.getOtherConnectedRemoteId=i8.prototype.aa;i8.prototype.H=function(){var a=this.o;return a.A.isActive()?a.A.A-(0,g.H)():window.NaN};
i8.prototype.getReconnectTimeout=i8.prototype.H;i8.prototype.ba=function(){return this.C||"UNSUPPORTED"};
i8.prototype.getAutoplayMode=i8.prototype.ba;i8.prototype.ga=function(){return this.G||""};
i8.prototype.getAutoplayVideoId=i8.prototype.ga;i8.prototype.wa=function(){if(!(0,window.isNaN)(this.H())){var a=this.o.A;g.zu(a.o);a.start()}};
i8.prototype.reconnect=i8.prototype.wa;i8.prototype.ma=function(a,b){o8(this,a,b);tFa(this)};
i8.prototype.sendMessage=i8.prototype.ma;g.C(p8,p7);g.h=p8.prototype;g.h.Ee=function(a){return this.ld.$_gs(a)};
g.h.contains=function(a){return!!this.ld.$_c(a)};
g.h.get=function(a){return this.ld.$_g(a)};
g.h.start=function(){this.ld.$_st()};
g.h.add=function(a,b,c){this.ld.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.ld.$_r(a,b,c)};
g.h.Kr=function(a,b,c,d){this.ld.$_un(a,b,c,d)};
g.h.X=function(){for(var a=0,b=this.A.length;a<b;++a)this.ld.$_ubk(this.A[a]);this.A.length=0;this.ld=null;p8.ea.X.call(this)};
g.h.FY=function(){this.V("screenChange")};
g.h.JU=function(){this.V("onlineScreenChange")};
y7.prototype.$_st=y7.prototype.start;y7.prototype.$_gspc=y7.prototype.GY;y7.prototype.$_gsppc=y7.prototype.lH;y7.prototype.$_c=y7.prototype.contains;y7.prototype.$_g=y7.prototype.get;y7.prototype.$_a=y7.prototype.add;y7.prototype.$_un=y7.prototype.Kr;y7.prototype.$_r=y7.prototype.remove;y7.prototype.$_gs=y7.prototype.Ee;y7.prototype.$_gos=y7.prototype.kH;y7.prototype.$_s=y7.prototype.subscribe;y7.prototype.$_ubk=y7.prototype.ce;var q8=null,r8=null,G8=null,v8=[];g.t(H8,g.L);g.h=H8.prototype;
g.h.X=function(){g.L.prototype.X.call(this);this.B.stop();this.D.stop();this.K.stop();this.N();this.o.unsubscribe("proxyStateChange",this.KE,this);this.o.unsubscribe("remotePlayerChange",this.Ln,this);this.o.unsubscribe("remoteQueueChange",this.Jq,this);this.o.unsubscribe("autoplayUpNext",this.gE,this);this.o.unsubscribe("previousNextChange",this.HE,this);this.o.unsubscribe("nowAutoplaying",this.yE,this);this.o.unsubscribe("autoplayDismissed",this.fE,this);this.o=this.C=null};
g.h.dD=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.o.o)if(K8(this)){if(!c8(this.o).isAdPlaying()||"control_seek"!=a)switch(a){case "control_toggle_play_pause":c8(this.o).qb()?this.o.pause():this.o.play();break;case "control_play":this.o.play();break;case "control_pause":this.o.pause();break;case "control_seek":this.J.Jm(c[0],c[1]);break;case "control_subtitles_set_track":L8(this,c[0]);break;case "control_set_audio_track":c=c[0],K8(this)&&this.o.Px(this.T.getVideoData(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.T.getCurrentTime();M8(this,0==c?void 0:c);break;case "control_seek":M8(this,c[0]);break;case "control_subtitles_set_track":L8(this,c[0]);break;case "control_set_audio_track":c=c[0],K8(this)&&this.o.Px(this.T.getVideoData(1).videoId,c)}};
g.h.FS=function(a){this.K.LL(a)};
g.h.gY=function(a){this.dD("control_subtitles_set_track",g.Zb(a)?null:a)};
g.h.tG=function(){var a=this.T.Fc("captions","track");g.Zb(a)||L8(this,a)};
g.h.uE=function(a){if(K8(this)){this.o.unsubscribe("remotePlayerChange",this.Ln,this);var b=Math.round(a.volume);a=!!a.muted;var c=c8(this.o);if(b!=c.volume||a!=c.muted)this.o.setVolume(b,a),this.L.start();this.o.subscribe("remotePlayerChange",this.Ln,this)}};
g.h.eU=function(){g.Zb(this.F)||OFa(this,this.F);this.G=!1};
g.h.KE=function(a,b){this.D.stop();2==b&&this.qG()};
g.h.Ln=function(){if(K8(this)){this.B.stop();var a=c8(this.o);switch(a.o){case 1080:case 1081:case 1084:case 1085:this.C.G=1;break;case 1082:case 1083:this.C.G=0;break;default:this.C.G=-1}switch(a.o){case 1081:case 1:J8(this,new g.TP(8));this.pG();break;case 1085:case 3:J8(this,new g.TP(9));break;case 1083:case 0:J8(this,new g.TP(2));this.J.stop();I8(this,this.T.getVideoData().lengthSeconds);break;case 1084:J8(this,new g.TP(4));break;case 2:J8(this,new g.TP(4));I8(this,Y7(a));break;case -1:J8(this,
new g.TP(64));break;case -1E3:J8(this,new g.TP(128,{errorCode:"mdx.remoteerror",message:"This video is not available for remote playback."}))}a=c8(this.o).A;var b=this.F;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.format==b.format&&a.kind==b.kind:1)||(this.F=a,OFa(this,a));a=c8(this.o);-1==a.volume||Math.round(this.T.getVolume())==a.volume&&this.T.isMuted()==a.muted||this.L.isActive()||this.TG()}else NFa(this)};
g.h.HE=function(){this.T.V("mdxpreviousnextchange")};
g.h.Jq=function(){K8(this)||NFa(this)};
g.h.PK=function(){this.o.gA()};
g.h.gE=function(a){a&&(a=g.DE("/watch_queue_ajax",{method:"GET",fd:{action_get_watch_queue_item:1,video_id:a},onSuccess:(0,g.B)(this.pW,this)}))&&(this.N=(0,g.B)(a.abort,a))};
g.h.pW=function(a,b){var c=new g.VO(g.X(this.T),{videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.T.V("mdxautoplayupnext",c)};
g.h.yE=function(a){(0,window.isNaN)(a)||this.T.V("mdxnowautoplaying",a)};
g.h.fE=function(){this.T.V("mdxautoplaycanceled")};
g.h.JQ=function(a,b){-1==c8(this.o).o?M8(this,a):b&&this.o.iH(a)};
g.h.TG=function(){if(K8(this)){var a=c8(this.o);this.A.Ha(this.O);a.muted?this.T.mute():this.T.vg();this.T.setVolume(a.volume);this.O=this.A.R(this.T,"onVolumeChange",this.uE)}};
g.h.pG=function(){this.B.stop();if(!this.o.la()){var a=c8(this.o);a.qb()&&J8(this,new g.TP(8));I8(this,Y7(a));this.B.start()}};
g.h.qG=function(){this.D.stop();this.B.stop();var a=this.o.C.getReconnectTimeout();2==this.o.o&&!(0,window.isNaN)(a)&&this.D.start()};g.t(N8,g.V);N8.prototype.D=function(a){QFa(this,a.state)};g.t(O8,g.BY);O8.prototype.K=function(){var a=this.T.Fc("remote","receivers");a&&1<a.length&&!this.T.Fc("remote","quickCast")?(this.H=g.jb(a,this.D,this),g.CY(this,(0,g.I)(a,this.D)),a=this.T.Fc("remote","currentReceiver"),this.If(this.D(a)),this.enable(!0)):this.enable(!1)};
O8.prototype.D=function(a){return a.key};
O8.prototype.Hf=function(a){return"cast-selector-receiver"==a?"Cast...":this.H[a].name};
O8.prototype.Fd=function(a){g.BY.prototype.Fd.call(this,a);this.T.Xd("remote","currentReceiver",this.H[a]);this.C.Pb()};g.t(P8,g.FU);g.h=P8.prototype;g.h.create=function(){HFa(g.XM(g.X(this.player)));this.D.push(g.fG("yt-remote-before-disconnect",this.BS,this));this.D.push(g.fG("yt-remote-connection-change",this.tV,this));this.D.push(g.fG("yt-remote-receiver-availability-change",this.IE,this));this.D.push(g.fG("yt-remote-auto-connect",this.rV,this));this.D.push(g.fG("yt-remote-receiver-resumed",this.qV,this));this.IE()};
g.h.load=function(){this.player.zv();g.FU.prototype.load.call(this);this.C=new H8(this,this.player,this.o);var a=(a=MFa())?a.currentTime:0;var b=F8()?new b8(A8(),void 0):null;0==a&&b&&(a=Y7(c8(b)));0!=a&&(this.J=a||0,this.player.V("progresssync",a,void 0));PFa(this,this.F,this.F);g.P_(this.player.app,6)};
g.h.unload=function(){this.player.V("mdxautoplaycanceled");this.B=this.A;g.nf(this.C,this.o);this.o=this.C=null;g.FU.prototype.unload.call(this);g.P_(this.player.app,5)};
g.h.X=function(){g.gG(this.D);g.FU.prototype.X.call(this)};
g.h.zn=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.C.dD.apply(this.C,[a].concat(g.fa(c)))};
g.h.GL=function(){return this.loaded?this.C.suggestion:null};
g.h.mg=function(){return this.o?c8(this.o).mg:!1};
g.h.hasNext=function(){return this.o?c8(this.o).hasNext:!1};
g.h.getCurrentTime=function(){return this.J};
g.h.xQ=function(){var a=c8(this.o),b=this.player.getVideoData();return{allowSeeking:g.X(this.player).experiments.o("web_player_mdx_allow_seeking_change_killswitch")?this.player.Zc():!a.isAdPlaying()&&this.player.Zc(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.F?a.C+W7(a):a.C,isPeggedToLive:1>=(a.F?a.B+W7(a):a.B)-this.getCurrentTime(),loaded:a.K,seekableEnd:a.F?a.B+W7(a):a.B,seekableStart:0<a.D?a.D+W7(a):a.D}};
g.h.yQ=function(){this.o&&this.o.gH()};
g.h.zQ=function(){this.o&&this.o.hH()};
g.h.BS=function(a){1==a&&(this.K=this.o?c8(this.o):null)};
g.h.tV=function(){var a=F8()?new b8(A8(),void 0):null;if(a){var b=this.B;this.loaded&&this.unload();this.o=a;this.K=null;b.key!=this.A.key&&(this.B=b,this.load())}else g.mf(this.o),this.o=null,this.loaded&&(this.unload(),(a=this.K)&&a.videoId==this.player.getVideoData().videoId&&this.player.IC(a.videoId,Y7(a)));this.player.V("videodatachange","newdata",this.player.getVideoData(),3)};
g.h.IE=function(){this.H=[this.A].concat(JFa());var a=B8()||this.A;Q8(this,a);this.player.ya("onMdxReceiversChange")};
g.h.rV=function(){var a=B8();Q8(this,a)};
g.h.qV=function(){this.B=B8()};
g.h.wQ=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.H;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?S7():Q8(this,b)),this.loaded?this.B:this.A;case "quickCast":return 2==this.H.length&&"cast-selector-receiver"==this.H[1].key?(b&&S7(),!0):!1}};
g.h.AQ=function(){g8(this.o,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.Hc=function(){return!1};g.CX.remote=P8;})(_yt_player);
